/* CSS/real DOM control contract. Layout rectangles are verified separately with CUA. */
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom'),root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/web-ui-alignment'));
const styles=['shell','creation','library'].map(name=>({name,text:fs.readFileSync(path.join(root,'backend/static/web',name+'.css'),'utf8')})),cases=[];
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name);}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
function domFixture(){return new JSDOM('<!doctype html>'+styles.map(s=>'<style>'+s.text+'</style>').join('')+`<main>
 <button id="shell" class="shell-button">确认</button><button id="shell-secondary" class="shell-button shell-secondary">取消</button><button id="account" class="site-account">我的账号</button><button id="brand" class="site-brand">废片新生所</button>
 <button id="shell-close" class="shell-dialog-close">关闭</button><button id="shell-link" class="shell-link">查看说明</button>
 <section class="creation-module"><button id="create" class="creation-button">开始生成</button><button id="create-secondary" class="creation-tab">返回</button><article class="creation-template-card"><button id="favorite" class="creation-link-button">收藏 ♡</button></article><input id="create-input" class="creation-input"><div class="creation-submit-bar"><p class="creation-note">余额 100 光子 · 本次预扣40光子</p><button class="creation-button">开始生成</button></div></section>
 <section class="web-library"><button id="lib" class="lib-button">下载照片</button><button id="lib-secondary" class="lib-button lib-secondary">查看对比</button><button id="compact" class="lib-button lib-small">下载</button><button id="link" class="lib-link">查看记录</button><button id="danger" class="lib-link lib-danger">删除</button><button id="lib-close" class="lib-dialog-close">关闭</button><button id="filter" class="lib-filter">全部</button><button id="photo" class="lib-photo-button"><img class="lib-image" alt="作品"></button><form class="lib-profile-form"><input id="profile" class="lib-input"><button class="lib-button">保存昵称</button></form><nav class="lib-account-links"><button id="account-link" class="lib-link">我的模板 ›</button></nav></section>
 </main>`,{url:'https://fixture.invalid',pretendToBeVisual:true});}
function cssRules(dom,width){const list=[];function visit(rules){for(const rule of rules){if(rule.media){const text=rule.media.mediaText,match=/max-width\s*:\s*(\d+)px/.exec(text);if(match&&width<=Number(match[1]))visit(rule.cssRules);}else if(rule.selectorText)list.push(rule);}}for(const sheet of dom.window.document.styleSheets)visit(sheet.cssRules);return list;}
function contract(dom,id,property,width){let value='';const node=dom.window.document.getElementById(id);for(const rule of cssRules(dom,width))if(rule.selectorText.split(',').some(s=>{try{return node.matches(s.trim());}catch(e){return false;}})){const set=rule.style.getPropertyValue(property);if(set)value=set;}return value;}
(async()=>{
 await test('primary_secondary_and_filter_controls_share_44px_height_and_centered_axes',()=>{const dom=domFixture();try{for(const id of ['shell','shell-secondary','account','brand','create','create-secondary','lib','lib-secondary','filter']){const css=dom.window.getComputedStyle(dom.window.document.getElementById(id));assert.equal(css.minHeight,'44px',id);assert.equal(css.display,'inline-flex',id);assert.equal(css.alignItems,'center',id);assert.equal(css.justifyContent,'center',id);assert.equal(css.lineHeight,'1.25',id);}}finally{dom.window.close();}});
 await test('compact_32px_and_icon_favorite_40px_are_explicit_desktop_variants',()=>{const dom=domFixture();try{for(const id of ['compact','link','shell-link'])assert.equal(contract(dom,id,'min-height',1200),'32px',id);for(const id of ['favorite','shell-close','lib-close'])assert.equal(contract(dom,id,'min-height',1200),'40px',id);}finally{dom.window.close();}});
 await test('mobile_compact_icon_and_favorite_touch_targets_raise_to_at_least_44px',()=>{const dom=domFixture();try{for(const id of ['compact','link','shell-link','favorite','shell-close','lib-close','account'])assert.equal(contract(dom,id,'min-height',390),'44px',id);}finally{dom.window.close();}});
 await test('control_surface_border_radius_and_primary_colors_match_across_modules',()=>{const dom=domFixture();try{const nodes=['shell','create','lib'].map(id=>dom.window.getComputedStyle(dom.window.document.getElementById(id)));assert(nodes.every(css=>css.borderRadius==='0px'));assert(nodes.every(css=>css.backgroundColor===nodes[0].backgroundColor));assert(nodes.every(css=>css.color===nodes[0].color));for(const id of ['shell-secondary','create-secondary','lib-secondary','filter'])assert.equal(dom.window.getComputedStyle(dom.window.document.getElementById(id)).borderRadius,'0px');}finally{dom.window.close();}});
 await test('single_line_form_inputs_and_inline_save_controls_keep_equal_minimum_heights',()=>{const dom=domFixture();try{for(const id of ['create-input','profile'])assert.equal(dom.window.getComputedStyle(dom.window.document.getElementById(id)).minHeight,'44px');assert.equal(dom.window.getComputedStyle(dom.window.document.querySelector('.lib-profile-form')).alignItems,'center');assert.equal(parseFloat(dom.window.getComputedStyle(dom.window.document.getElementById('profile')).minWidth),0);}finally{dom.window.close();}});
 await test('photo_buttons_remain_block_and_account_menu_labels_remain_left_aligned',()=>{const dom=domFixture();try{assert.equal(dom.window.getComputedStyle(dom.window.document.getElementById('photo')).display,'block');assert.equal(dom.window.getComputedStyle(dom.window.document.getElementById('account-link')).justifyContent,'flex-start');for(const id of ['create','shell','lib'])assert.notEqual(contract(dom,id,'width',1200),'100%');}finally{dom.window.close();}});
 await test('danger_disabled_focus_and_pending_readonly_semantics_are_preserved',async()=>{const dom=domFixture();try{assert.equal(dom.window.getComputedStyle(dom.window.document.getElementById('danger')).color,'rgb(158, 75, 60)');assert(styles.some(s=>s.text.includes(':focus-visible')));assert(styles.some(s=>s.text.includes(':disabled')));}finally{dom.window.close();}const {mountTemplateSharing}=await import(pathToFileURL(path.join(root,'backend/static/web/template-sharing.js')).href);const view=new JSDOM('<main></main>',{url:'https://fixture.invalid'}),doc=view.window.document;const row={id:'share',revision:1,status:'pending',name:'待审',prompt:'水彩',guide:{},covers:[]};const ctx={accountVersion:1,state:{user:{account_user_id:'owner'}},document:doc,requireLogin:async()=>true,element:(tag,cls,text)=>{const node=doc.createElement(tag);node.className=cls||'';if(text!=null)node.textContent=text;return node;},api:async()=>({submission:row}),toast(){},navigate(){},confirm:async()=>true};const stop=await mountTemplateSharing(ctx,doc.querySelector('main'),'template-share',{id:'share'});for(let i=0;i<4;i++)await new Promise(r=>setImmediate(r));assert(Array.from(doc.querySelectorAll('form button,form input,form textarea')).every(n=>n.disabled));assert(!Array.from(doc.querySelectorAll('button')).find(n=>n.textContent==='撤回此模板').disabled);stop();view.window.close();});
 await test('mobile_fixed_cta_preserves_safe_area_offset_flow_reserve_and_separate_amount_row',()=>{const text=styles.find(s=>s.name==='creation').text;assert(text.includes('padding-bottom:calc(230px + env(safe-area-inset-bottom))'));assert(text.includes('position:fixed; bottom:calc(76px + env(safe-area-inset-bottom))'));assert(/creation-submit-bar>\.creation-note\s*\{[^}]*flex:1 0 100%[^}]*margin:0[^}]*text-align:center/.test(text));assert(/creation-submit-bar>\.creation-button\s*\{[^}]*flex:1 0 100%/.test(text));});
 await test('native_file_picker_and_browser_button_pseudo_metrics_have_clean_margins',()=>{const shell=styles.find(s=>s.name==='shell').text,creation=styles.find(s=>s.name==='creation').text;assert(shell.includes('button::before,button::after'));assert(shell.includes('button::-moz-focus-inner { border:0; padding:0; }'));assert(creation.includes('::file-selector-button'));assert(creation.includes('margin:0 10px 0 0'));assert(creation.includes('.creation-input[type=file] { padding:0; border:0; background:transparent; }'));});
 await test('alignment_change_adds_no_remote_assets_filters_or_new_animations',()=>{const text=styles.map(x=>x.text).join('\n');assert(!/@import|@font-face|https?:\/\//.test(text));assert(!/@keyframes/.test(text));assert(!/filter\s*:\s*(drop-shadow|brightness|saturate)/.test(text));});
 await test('real_catalog_hot_hides_shuffle_random_reveals_and_hot_hides_again',async()=>{const {mountCreation}=await import(pathToFileURL(path.join(root,'backend/static/web/creation.js')).href);const dom=new JSDOM(styles.map(s=>'<style>'+s.text+'</style>').join('')+'<main></main>',{url:'https://fixture.invalid',pretendToBeVisual:true}),doc=dom.window.document;const ctx={accountVersion:1,state:{user:null,config:{prices:{light:40,fine:40},text_generation:{price:40}}},document:doc,requireLogin:async()=>false,navigate(){},toast(){},element:(tag,cls,text)=>{const n=doc.createElement(tag);n.className=cls||'';if(text!=null)n.textContent=text;return n;},api:async()=>({groups:[],items:[{id:'fixture',name:'样例',source:'official'}]})};const stop=await mountCreation(ctx,doc.querySelector('main'),'templates');for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));try{const select=doc.querySelector('[aria-label="模板排序"]'),shuffle=Array.from(doc.querySelectorAll('button')).find(n=>n.textContent==='换一批');assert(shuffle);assert.equal(select.value,'hot');assert(shuffle.hidden);assert.equal(dom.window.getComputedStyle(shuffle).display,'none');select.value='random';select.dispatchEvent(new dom.window.Event('change'));assert(!shuffle.hidden);assert.equal(dom.window.getComputedStyle(shuffle).display,'inline-flex');select.value='hot';select.dispatchEvent(new dom.window.Event('change'));assert(shuffle.hidden);assert.equal(dom.window.getComputedStyle(shuffle).display,'none');}finally{stop();dom.window.close();}});
 await test('hidden_auth_balance_filter_buttons_and_module_roots_stay_hidden_with_standalone_css',()=>{const fixtures={shell:'<span class="site-balance" hidden>余额</span><label class="shell-field" hidden><input></label><button class="shell-button" hidden>提交</button>',creation:'<section class="creation-module"><button class="creation-link-button" hidden>隐藏按钮</button><input class="creation-input" hidden></section><section class="creation-module" hidden>隐藏页</section>',library:'<section class="web-library"><button class="lib-filter" hidden>隐藏筛选</button><button class="lib-link" hidden>隐藏更多</button></section><section class="web-library" hidden>隐藏页</section>'};for(const stylesheet of styles){const dom=new JSDOM('<style>'+stylesheet.text+'</style>'+fixtures[stylesheet.name]);try{for(const node of dom.window.document.querySelectorAll('[hidden]'))assert.equal(dom.window.getComputedStyle(node).display,'none',stylesheet.name+' '+node.className);const rules=Array.from(dom.window.document.styleSheets[0].cssRules).filter(r=>r.selectorText&&r.selectorText.includes('[hidden]'));assert(rules.some(r=>r.style.getPropertyPriority('display')==='important'));}finally{dom.window.close();}}});
 fs.mkdirSync(out,{recursive:true});const passed=cases.filter(c=>c.passed).length;fs.writeFileSync(path.join(out,'web_ui_alignment_results.json'),JSON.stringify({summary:{total:cases.length,passed,failed:cases.length-passed},css_bytes:styles.map(s=>({file:s.name+'.css',bytes:Buffer.byteLength(s.text)})),cases},null,2),'utf8');console.log(`WEB_UI_ALIGNMENT_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1;});
