/* Real admin HTML/script in jsdom; credentials/API/cover media are synthetic. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const {JSDOM,VirtualConsole}=require(process.env.WEB_DOM_MODULE||'jsdom'),root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/template-share-admin'));
const tick=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));},cases=[];
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name);}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
function fixture({failure=false}={}){
 const calls=[],errors=[],virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>errors.push(e.message));
 const row={id:'share_1',revision:3,status:'pending',name:'<img src=x onerror=alert(1)>',subtitle:'示例',prompt:'水彩</textarea><script>window.bad=true</script>',author_name:'作者',guide:{advice:'清晰',suitable:['单人'],unsuitable:['遮挡'],tips:['原图']},covers:[{preview_url:'https://cos.invalid/full',thumbnail_url:'https://cos.invalid/small'}],has_published:true,published_revision:2,group_id:'',reward_summary:{reward_earned:80,reward_credited:40,reward_offset:40,recovery_due:20}};
 const settings={template_sharing:{enabled:true,reward_enabled:true,reward_amount:40,reward_mode:'first_user',author_daily_cap:400,global_daily_cap:4000}};
 const dom=new JSDOM(fs.readFileSync(path.join(root,'backend/admin.html'),'utf8'),{url:'https://site.invalid/admin',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse(window){window.confirm=()=>true;window.fetch=async(url,init={})=>{calls.push({url,init,data:init.body&&JSON.parse(init.body)});let status=200,data={};
  if(url==='/admin/api/session'){status=401;data={detail:'fixture gate'};}
  else if(url==='/admin/api/settings'){if(init.method==='PUT')Object.assign(settings,JSON.parse(init.body));data=settings;}
  else if(url==='/admin/api/template-groups')data={items:[{id:'art',name:'艺术',enabled:true},{id:'off',name:'关闭',enabled:false}]};
  else if(url==='/admin/api/templates')data={items:[{id:'official_tpl',name:'官方模板',group_id:'art',enabled:true,source:'official'},{id:'user_tpl',name:'用户模板',group_id:'',enabled:true,source:'user'}]};
  else if(url.startsWith('/admin/api/template-shares?'))data={items:[row],total:1,has_more:false};
  else if(url.endsWith('/review')){status=failure?409:200;data=failure?{detail:'版本已变化'}:{submission:{...row,status:'approved'}};}
  else if(url==='/admin/api/template-shares/share_1')data={submission:row};
  return {ok:status<400,status,json:async()=>data};};}});
 return {dom,doc:dom.window.document,row,settings,calls,errors,finish(){dom.window.close();}};
}
(async()=>{
 await test('admin_review_entry_is_separate_from_official_templates_and_lazily_loaded',async()=>{const f=fixture();await tick();assert(f.doc.querySelector('[data-page="tshare"]'));assert(!f.calls.some(x=>x.url.includes('/template-shares')));f.dom.window.showPage('tshare');await tick();assert(f.calls.some(x=>x.url==='/admin/api/template-shares?limit=24&offset=0&status=pending'));assert(f.doc.body.textContent.includes('奖励只给作者'));f.finish();});
 await test('review_render_escapes_name_prompt_author_and_keeps_cover_https',async()=>{const f=fixture();await tick();await f.dom.window.editTemplateShare('share_1');assert.equal(f.doc.querySelector('#ts-edit-prompt').value,f.row.prompt);assert(!f.dom.window.bad);assert(f.doc.querySelector('#modal-root img').src.startsWith('https://cos.invalid'));assert.equal(f.doc.querySelectorAll('#ts-edit-group option').length,2);f.finish();});
 await test('approve_posts_expected_revision_and_content_only_patch_without_upfront_reward',async()=>{const f=fixture();await tick();await f.dom.window.editTemplateShare('share_1');f.doc.querySelector('#ts-edit-name').value='水彩模板';f.doc.querySelector('#ts-approve').click();await tick();const req=f.calls.find(x=>x.url.endsWith('/review'));assert.equal(req.data.revision,3);assert.equal(req.data.action,'approve');assert.deepEqual(Object.keys(req.data.patch).sort(),['group_id','guide','name','prompt','subtitle']);assert(!('reward' in req.data));assert.equal(req.init.credentials,'same-origin');assert.equal(req.init.headers['X-Admin-Request'],'1');f.finish();});
 await test('reject_requires_reason_and_retains_approved_old_version_explanation',async()=>{const f=fixture();await tick();await f.dom.window.editTemplateShare('share_1');assert(f.doc.querySelector('#modal-root').textContent.includes('上一版继续公开'));f.doc.querySelector('#ts-reject').click();await tick();assert(!f.calls.some(x=>x.url.endsWith('/review')));f.doc.querySelector('#ts-edit-reason').value='封面与效果不符';f.doc.querySelector('#ts-reject').click();await tick();const req=f.calls.find(x=>x.url.endsWith('/review'));assert.equal(req.data.action,'reject');assert.equal(req.data.reason,'封面与效果不符');f.finish();});
 await test('revision_conflict_keeps_editable_content_and_does_not_claim_approval',async()=>{const f=fixture({failure:true});await tick();await f.dom.window.editTemplateShare('share_1');f.doc.querySelector('#ts-edit-name').value='保留输入';f.doc.querySelector('#ts-approve').click();await tick();assert.equal(f.doc.querySelector('#ts-edit-name').value,'保留输入');assert(f.doc.querySelector('#ts-edit-message').textContent.includes('版本已变化'));assert(!f.doc.querySelector('#ts-approve').disabled);f.finish();});
 await test('unpublish_posts_separate_action_with_revision_and_confirmation',async()=>{const f=fixture();await tick();await f.dom.window.editTemplateShare('share_1');f.doc.querySelector('#ts-unpublish').click();await tick();const req=f.calls.find(x=>x.url.endsWith('/review'));assert.equal(req.data.action,'unpublish');assert.equal(req.data.revision,3);f.finish();});
 await test('author_recovery_summary_is_read_only_and_not_existing_balance_clawback',async()=>{const f=fixture();await tick();await f.dom.window.editTemplateShare('share_1');assert(f.doc.querySelector('#modal-root').textContent.includes('不扣已有余额'));assert(f.doc.querySelector('#modal-root').textContent.includes('已到账 40'));assert(!f.calls.some(x=>x.url.includes('/users/')));f.finish();});
 await test('reward_config_saves_exact_seven_fields_using_settings_put',async()=>{const f=fixture();await tick();f.dom.window.showPage('tshare');await tick();f.doc.querySelector('#ts-reward-amount').value='40';f.doc.querySelector('#ts-author-cap').value='400';f.doc.querySelector('#ts-global-cap').value='4000';f.doc.querySelector('#ts-reward-mode').value='all_success';f.doc.querySelector('#ts-save-settings').click();await tick();const req=f.calls.find(x=>x.url==='/admin/api/settings'&&x.init.method==='PUT');assert.deepEqual(req.data.template_sharing,{enabled:true,reward_enabled:true,reward_amount:40,reward_mode:'all_success',author_daily_cap:400,global_daily_cap:4000});assert.deepEqual(Object.keys(req.data),['template_sharing']);f.finish();});
 await test('invalid_reward_values_do_not_submit_settings_or_adjust_balance',async()=>{const f=fixture();await tick();f.dom.window.showPage('tshare');await tick();f.doc.querySelector('#ts-reward-amount').value='-1';f.doc.querySelector('#ts-save-settings').click();await tick();assert(!f.calls.some(x=>x.url==='/admin/api/settings'&&x.init.method==='PUT'));assert(!f.calls.some(x=>x.url.includes('/users/')));f.finish();});
 await test('generic_template_panel_user_projection_is_read_only_and_jumps_to_review',async()=>{const f=fixture();await tick();await f.dom.window.loadTemplates();const row=f.doc.querySelector('#tpl-table tbody').rows[1];assert(row.textContent.includes('用户分享 · 只读投影'));assert(!row.textContent.includes('编辑'));assert(!row.textContent.includes('删除'));assert(row.querySelector('input[type="checkbox"]').disabled);await f.dom.window.delTpl('user_tpl');assert(!f.calls.some(x=>x.url==='/admin/api/templates/user_tpl'));row.querySelector('button').click();await tick();assert.equal(f.doc.querySelector('#page-tshare').hidden,false);assert.equal(f.doc.querySelector('#ts-status').value,'all');f.finish();});
 await test('guide_validation_matches_eight_lines_and_sixty_characters_without_erasing_editor',async()=>{const f=fixture();await tick();await f.dom.window.editTemplateShare('share_1');f.doc.querySelector('#ts-edit-name').value='模板';f.doc.querySelector('#ts-edit-suitable').value='长'.repeat(61);f.doc.querySelector('#ts-approve').click();await tick();assert(!f.calls.some(x=>x.url.endsWith('/review')));assert(f.doc.querySelector('#ts-edit-message').textContent.includes('60字'));assert.equal(f.doc.querySelector('#ts-edit-suitable').value.length,61);f.finish();});
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'template_share_admin_results.json'),JSON.stringify({summary:{total:cases.length,passed:cases.filter(x=>x.passed).length,failed:cases.filter(x=>!x.passed).length},cases},null,2));const passed=cases.filter(x=>x.passed).length;console.log(`TEMPLATE_SHARE_ADMIN_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1;});
