/* Web creation behavior with real production module and isolated DOM/IDB/COS doubles. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),cp=require('child_process');
const root=path.resolve(process.env.REVIEW_ROOT||path.resolve(__dirname,'../..'));
const output=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/web-creation-parity'));
const source=fs.readFileSync(path.join(root,'backend/static/web/creation.js'),'utf8');
const sharedSource=fs.readFileSync(path.join(root,'backend/static/web/shared-load.js'),'utf8').replace(/\bexport (?=(?:async )?function|class)/g,'');
const tick=()=>new Promise(r=>setImmediate(r));const rows=[];
class Element {
  constructor(tag,cls='',text=''){this.tagName=tag.toUpperCase();this.className=cls;this.textContent=text;this.children=[];this.listeners={};this.style={};this.dataset={};this.value='';this.disabled=false;this.files=[];this.classList={add:v=>this.className+=' '+v};}
  append(...children){for(const child of children){child.parent=this;this.children.push(child);}}
  prepend(...children){children.forEach(c=>c.parent=this);this.children.unshift(...children);}
  replaceChildren(...children){this.children=[];this.append(...children);}
  remove(){if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);}
  setAttribute(k,v){this[k]=v;}addEventListener(k,fn){(this.listeners[k]||=[]).push(fn);}
  async dispatch(k){for(const fn of this.listeners[k]||[])await fn({target:this});}
  async click(){if(!this.disabled)await this.dispatch('click');}showModal(){this.open=true;}close(){this.open=false;this.dispatch('close');}
  get options(){return this.children.filter(c=>c.tagName==='OPTION');}
  querySelectorAll(selector){const parts=selector.split(',');const match=node=>parts.some(s=>s.startsWith('.')?node.className.split(' ').includes(s.slice(1)):node.tagName.toLowerCase()===s);const found=[];for(const child of this.children){if(match(child))found.push(child);found.push(...child.querySelectorAll(selector));}return found;}
  querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
}
function idbFixture(){
  const values=new Map();let fail=false;
  const db={objectStoreNames:{contains:()=>true},createObjectStore(){},transaction(){const tx={};let op;
    tx.objectStore=()=>({get(key){const request={};op=()=>{request.result=values.get(key);request.onsuccess&&request.onsuccess();};queueMicrotask(()=>{op();queueMicrotask(()=>tx.oncomplete&&tx.oncomplete());});return request;},
      put(value,key){const request={};queueMicrotask(()=>{request.onsuccess&&request.onsuccess();queueMicrotask(()=>{if(fail)tx.onabort&&tx.onabort();else{values.clear();values.set(key,structuredClone(value));tx.oncomplete&&tx.oncomplete();}});});return request;},
      delete(key){const request={};queueMicrotask(()=>{values.delete(key);request.onsuccess&&request.onsuccess();queueMicrotask(()=>tx.oncomplete&&tx.oncomplete());});return request;}});return tx;}};
  return {factory:{open(){const request={result:db};queueMicrotask(()=>request.onsuccess&&request.onsuccess());return request;}},values,fail:()=>fail=true};
}
function fixture(options={}){
  const calls=[],messages=[],navigation=[],storage=new Map(),idb=idbFixture();let serial=0,storageFail=false,modalDecision=true;
  const config={prices:{light:40,fine:80},free_mode:false,cos_ready:true,template_quality_options:['light','fine'],template_output_modes:['template','single'],text_generation:{ready:true,price:40}};
  const user=options.guest?null:{user_id:'WEB-1111111111111111',balance:200};
  const catalog={groups:[{id:'art',name:'艺术'},{id:'photo',name:'修复'}],items:[{id:'poster',name:'旅行海报',subtitle:'水彩风格',group_id:'art',usage_count:8,cover:'https://cos.invalid/cover',text_fields:[{key:'title',label:'标题',max_len:20,default:'旅行'}],guide:{advice:'五官清楚',suitable:['单人照片'],unsuitable:['严重遮挡']}},{id:'clear',name:'清晰通透',group_id:'photo',usage_count:2}]};
  const api=async(url,opts={})=>{calls.push({url,opts});if(options.api)return options.api(url,opts,config,calls);
    if(url==='/api/config')return structuredClone(config);if(url==='/api/me')return {balance:ctx.state.user&&ctx.state.user.balance||0};if(url==='/api/templates')return catalog;
    if(url==='/api/me/preferences')return {template_favorites:['poster'],recent_templates:['clear','poster']};if(url==='/api/uploads')return {url:'https://cos.invalid/upload',upload_id:'ticket'};
    if(url.includes('/complete'))return {code:0};if(url==='/api/text-generation'||url==='/api/rescue/by-upload')return {code:0,job_id:'accepted',balance:160,status:'processing'};
    if(url.startsWith('/api/me/submissions/'))return {state:'pending',job_id:null};if(url.startsWith('/api/jobs/'))return {status:'succeeded',input_mode:'photo',orig_url:'https://cos.invalid/comparison',result_url:'https://cos.invalid/result',width:100,height:100};return {};};
  const ctx={accountVersion:1,state:{user,config},api,requireLogin:async()=>!!ctx.state.user,navigate:(r,p)=>navigation.push({route:r,params:p}),toast:s=>messages.push(s),confirm:async()=>modalDecision,
    setBalance:n=>{if(ctx.state.user)ctx.state.user.balance=n;},invalidateAccount(){calls.push({invalidated:true});},element:(t,c,s)=>new Element(t,c,s)};
  const fetch=async(url,opts={})=>{calls.push({cos:url,opts});if(options.fetch)return options.fetch(url,opts);return {ok:true,status:200,blob:async()=>new Blob(['pixels'],{type:'image/jpeg'})};};
  const module={exports:{}};const sandbox={module,console,setTimeout,clearTimeout,Promise,Date:options.Date||Date,Math,Blob,URL:Object.assign(class URL extends globalThis.URL {},{createObjectURL:()=> 'blob:'+ ++serial,revokeObjectURL(){}}),
    crypto:{randomUUID:()=>String(++serial).padStart(32,'a')},location:{origin:'https://site.invalid'},fetch,indexedDB:idb.factory,
    localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{if(storageFail)throw new Error('quota');storage.set(k,v);},removeItem:k=>storage.delete(k)}};
  vm.runInNewContext(sharedSource+'\n'+source.replace(/^import .*;\r?\n/gm,'').replace(/\bexport (?=(?:async )?function|class)/g,'')+'\nmodule.exports={CreationSession,createReceiptStore,createDraftStore,mountCreation};',sandbox);
  const production=module.exports;ctx.creationOptions={receipts:production.createReceiptStore(sandbox.localStorage),drafts:production.createDraftStore(idb.factory),fetch};
  return {ctx,config,catalog,production,session:()=>new production.CreationSession(ctx,ctx.creationOptions),calls,messages,navigation,storage,idb,failStorage:()=>storageFail=true,denyConfirm:()=>modalDecision=false};
}
const text=()=>({input_mode:'text',prompt:'森林小屋',aspect_ratio:'1:1',quality:'light',rights:false,blob:null});
const photo=()=>({input_mode:'photo',blob:new Blob(['photo'],{type:'image/jpeg'}),quality:'light',template_id:'',text_fields:{},custom_prompt:'移除路人',show_custom_prompt:false,aspect_ratio:'original',template_output_mode:'template',rights:true});
async function test(name,fn){try{await fn();rows.push({case:name,passed:true});console.log('PASS '+name);}catch(e){rows.push({case:name,passed:false,error:String(e.stack)});console.error('FAIL '+name,e.message);}}
module.exports={fixture,Element,text,photo,tick};
if(require.main===module)(async()=>{
  await test('production_esm_module_parses_without_a_framework',()=>cp.execFileSync(process.execPath,['--input-type=module','--check'],{input:source}));
  await test('guest_can_browse_templates_but_cannot_submit_or_gain_balance',async()=>{const f=fixture({guest:true}),s=f.session();await s.catalog();assert.equal(s.templates.length,2);assert.equal(await s.submit(text(),40),null);assert(!f.calls.some(c=>c.url==='/api/text-generation'));assert.equal(f.ctx.state.user,null);});
  await test('catalog_search_category_favorite_and_recent_filters_use_real_data',async()=>{const f=fixture(),s=f.session();await s.catalog();await s.loadPreferences();assert.equal(s.filter('水彩','art')[0].id,'poster');assert.equal(s.filter('','all','favorites')[0].id,'poster');assert.equal(s.filter('','all','recent')[0].id,'clear');});
  await test('missing_selected_template_never_falls_back_to_first_or_restore',async()=>{const f=fixture(),s=f.session();await assert.rejects(s.catalog('deleted'),/下架/);const d=photo();d.template_id='deleted';await assert.rejects(s.submit(d,40),/所选风格尚未确认/);assert(!f.calls.some(c=>c.url==='/api/uploads'));});
  await test('changed_price_requires_explicit_second_confirmation_no_paid_post',async()=>{const f=fixture(),s=f.session();f.config.text_generation.price=80;await assert.rejects(s.submit(text(),40),e=>e.code==='PRICE_CHANGED');assert(!f.calls.some(c=>c.url==='/api/text-generation'));await s.submit(text(),80);const post=f.calls.find(c=>c.url==='/api/text-generation');assert.equal(post.opts.data.expected_price,80);});
  await test('zero_balance_is_not_a_guest_reward_or_free_generation',async()=>{const f=fixture(),s=f.session();f.ctx.state.user.balance=0;await assert.rejects(s.submit(text(),40),e=>e.status===402);assert(!f.calls.some(c=>c.url==='/api/text-generation'));});
  await test('receipt_quota_failure_stops_every_billable_post',async()=>{const f=fixture(),s=f.session();f.failStorage();await assert.rejects(s.submit(text(),40),/回执未保存/);assert(!f.calls.some(c=>c.url==='/api/text-generation'));});
  await test('indexeddb_commit_quota_failure_does_not_start_generation',async()=>{const f=fixture(),s=f.session();f.idb.fail();await assert.rejects(s.submit(photo(),40),/草稿保存未完成/);assert(!f.calls.some(c=>c.url==='/api/uploads'));assert(!f.calls.some(c=>c.url==='/api/rescue/by-upload'));});
  await test('indexeddb_keeps_exactly_one_blob_and_uses_owner_boundary',async()=>{const f=fixture(),s=f.session();await s.saveDraft(photo());await s.saveDraft({...photo(),custom_prompt:'更新'});assert.equal(f.idb.values.size,1);assert.equal((await s.readDraft()).custom_prompt,'更新');assert.equal(await f.ctx.creationOptions.drafts.read('other-account'),null);});
  await test('photo_uses_cos_put_complete_by_upload_with_no_server_multipart',async()=>{const f=fixture(),s=f.session();await s.catalog();await s.submit(photo(),40);const put=f.calls.find(c=>c.cos&&c.opts.method==='PUT');assert(put);assert.equal(put.opts.credentials,'omit');assert(!put.opts.headers.Authorization);const post=f.calls.find(c=>c.url==='/api/rescue/by-upload');assert(post.opts.data.client_request_id);assert.equal(post.opts.data.expected_price,40);assert.equal(post.opts.data.custom_prompt,'');assert(!f.calls.some(c=>c.url==='/api/rescue'));});
  await test('rights_confirmation_prevents_upload_and_is_not_restored_as_granted',async()=>{const f=fixture(),s=f.session();await assert.rejects(s.submit({...photo(),rights:false},40),/使用权/);assert(!f.calls.some(c=>c.url==='/api/uploads'));await s.submit(photo(),40);assert.equal((await s.readDraft()).rights,false);});
  await test('template_output_text_and_tiers_match_mini_program_payload',async()=>{const f=fixture(),s=f.session();await s.catalog();const d=photo();Object.assign(d,{template_id:'poster',quality:'fine',template_output_mode:'single',text_fields:{title:'个人标题'},aspect_ratio:'9:16'});await s.submit(d,80);const post=f.calls.find(c=>c.url==='/api/rescue/by-upload');assert.equal(post.opts.data.template_output_mode,'single');assert.equal(post.opts.data.text_fields,JSON.stringify({title:'个人标题'}));assert.equal(post.opts.data.aspect_ratio,'');assert.equal(post.opts.data.quality,'fine');});
  await test('lost_post_response_is_persistent_and_does_not_auto_repost_after_remount',async()=>{let posts=0;const f=fixture();const base=f.ctx.api;f.ctx.api=async(url,opts)=>{if(url==='/api/text-generation'){posts++;throw new Error('timeout');}return base(url,opts);};const s=f.session();await assert.rejects(s.submit(text(),40),e=>e.code==='UNCERTAIN');const id=s.receipt().client_request_id;s.close();const next=f.session();await assert.rejects(next.submit(text(),40),e=>e.code==='UNCERTAIN');assert.equal(posts,1);assert.equal(next.receipt().client_request_id,id);});
  await test('submission_lookup_finds_exact_accepted_job_and_never_posts_again',async()=>{const f=fixture(),s=f.session();const receipt={owner:s.owner,client_request_id:'wc_original_submission',input_mode:'text',payload:{prompt:'小屋',aspect_ratio:'1:1',expected_price:40},draft:text(),state:'uncertain'};s.receipts.write(s.owner,receipt);const base=f.ctx.api;f.ctx.api=async(url,opts)=>url.startsWith('/api/me/submissions/')?{state:'accepted',job_id:'same_job',balance:120}:base(url,opts);const found=await s.submit(text(),40);assert.equal(found.job_id,'same_job');assert.equal(f.ctx.state.user.balance,120);assert(!f.calls.some(c=>c.url==='/api/text-generation'));});
  await test('not_found_is_manual_retry_only_with_same_request_number',async()=>{const f=fixture(),s=f.session();const receipt={client_request_id:'wc_original_submission',input_mode:'text',payload:{prompt:'冻结描述',aspect_ratio:'1:1',expected_price:40},draft:{...text(),prompt:'冻结描述'},state:'uncertain'};s.receipts.write(s.owner,receipt);const base=f.ctx.api;f.ctx.api=async(url,opts)=>{if(url.startsWith('/api/me/submissions/'))throw Object.assign(new Error('not found'),{status:404});return base(url,opts);};await assert.rejects(s.submit(text(),40),e=>e.code==='UNCERTAIN');assert(!f.calls.some(c=>c.url==='/api/text-generation'));await s.submit(text(),40,{retry:true});const post=f.calls.find(c=>c.url==='/api/text-generation');assert.equal(post.opts.data.client_request_id,receipt.client_request_id);assert.equal(post.opts.data.prompt,'冻结描述');});
  await test('pending_receipts_are_strictly_per_user_even_after_account_switch',async()=>{const f=fixture(),s=f.session();s.receipts.write(s.owner,{client_request_id:'wc_original_submission',input_mode:'text',payload:{prompt:'私有'},draft:text(),state:'uncertain'});f.ctx.state.user={user_id:'WEB-2222222222222222',balance:0};f.ctx.accountVersion++;assert.equal(f.session().receipt(),null);assert(!s.active());});
  await test('late_post_response_cannot_change_new_account_or_visible_route',async()=>{let finish;const f=fixture(),s=f.session(),base=f.ctx.api;f.ctx.api=async(url,opts)=>url==='/api/text-generation'?new Promise(r=>finish=r):base(url,opts);const submitting=s.submit(text(),40);await tick();f.ctx.accountVersion++;f.ctx.state.user={user_id:'WEB-2222222222222222',balance:0};finish({job_id:'old_job',balance:160});await assert.rejects(submitting,e=>e.code==='INACTIVE');assert.equal(f.ctx.state.user.balance,0);assert.equal(f.navigation.length,0);});
  await test('complete_recipe_downloads_full_raw_original_not_status_comparison',async()=>{const f=fixture(),s=f.session();const recipe={complete:true,input_mode:'photo',job_id:'job',orig_url:'https://cos.invalid/raw-original',quality:'fine',template_id:'poster',text_fields:{title:'沿用'},custom_prompt:'',aspect_ratio:'',template_output_mode:'single'};const d=await s.recipe(recipe);assert.equal(d.quality,'fine');assert.equal(d.text_fields.title,'沿用');assert.equal(d.rights,false);assert(f.calls.some(c=>c.cos===recipe.orig_url));assert(!f.calls.some(c=>c.url==='/api/jobs/job'));});
  await test('expired_signature_refreshes_raw_recipe_once_without_comparison_fallback',async()=>{const f=fixture({fetch:async url=>url.endsWith('/old')?{ok:false,status:403}:{ok:true,status:200,blob:async()=>new Blob(['raw'],{type:'image/jpeg'})}}),s=f.session();const base=f.ctx.api;f.ctx.api=async(url,opts)=>url.endsWith('/recipe')?{complete:true,orig_url:'https://cos.invalid/fresh',job_id:'job'}:base(url,opts);await s.original({complete:true,job_id:'job',orig_url:'https://cos.invalid/old'});assert.equal(f.calls.filter(c=>c.cos).length,2);assert(!f.calls.some(c=>c.cos==='https://cos.invalid/comparison'));});
  await test('legacy_recipe_cannot_fabricate_historical_description',async()=>{const f=fixture(),s=f.session();await assert.rejects(s.recipe({complete:false,input_mode:'text',prompt:null}),/参数不完整/);assert.equal(f.idb.values.size,0);});
  await test('cleanup_stops_poll_and_late_metadata_does_not_repaint',async()=>{let finish,ticks=0;const f=fixture(),s=f.session();f.ctx.api=()=>new Promise(r=>finish=r);const polling=s.poll('job',()=>ticks++);s.close();finish({status:'succeeded'});await assert.rejects(polling,e=>e.code==='INACTIVE');assert.equal(ticks,0);});
  await test('mobile_form_controls_have_labels_rights_and_no_hidden_default_charge',async()=>{const f=fixture(),view=new Element('main');const cleanup=await f.production.mountCreation(f.ctx,view,'create');await tick();const file=view.querySelector('input');assert.equal(file.type,'file');assert.equal(file.accept,'image/*');assert.equal(file['aria-label'],'选择照片');const rights=view.querySelectorAll('input').find(n=>n.dataset.confirmRights);assert(rights);assert.equal(rights.checked,false);assert(view.querySelectorAll('select').some(n=>n.options.some(o=>o.value==='original')));cleanup();});
  await test('text_examples_require_confirmation_before_replacing_input',async()=>{const f=fixture(),view=new Element('main');const cleanup=await f.production.mountCreation(f.ctx,view,'text',{initialDraft:{...text(),prompt:'我的描述'}});await tick();const example=view.querySelectorAll('button').find(n=>n.textContent==='水彩风景');f.denyConfirm();await example.click();assert.equal(view.querySelector('textarea').value,'我的描述');assert.equal(view.querySelector('textarea').maxLength,500);cleanup();});
  await test('template_search_does_not_overwrite_existing_personal_draft',async()=>{const f=fixture(),s=f.session();await s.saveDraft(photo());const view=new Element('main'),cleanup=await f.production.mountCreation(f.ctx,view,'templates');await tick();const search=view.querySelector('input');search.value='海报';await search.dispatch('input');await new Promise(r=>setTimeout(r,350));const saved=await s.readDraft();assert(saved.blob);assert.equal(saved.input_mode,'photo');cleanup();});
  await test('missing_template_ui_disables_generation_and_keeps_requested_choice',async()=>{const f=fixture(),view=new Element('main');const cleanup=await f.production.mountCreation(f.ctx,view,'create',{templateId:'deleted'});await tick();const submit=view.querySelectorAll('button').find(n=>n.textContent==='开始生成');assert(submit.disabled);assert(view.querySelectorAll('option').some(n=>n.value==='deleted'&&n.selected));cleanup();});
  await test('small_screen_css_has_single_column_touch_targets_and_safe_area',()=>{const css=fs.readFileSync(path.join(root,'backend/static/web/creation.css'),'utf8');assert(css.includes('@media(max-width:700px)'));assert(css.includes('grid-template-columns:minmax(0,1fr)'));assert(css.includes('min-height:48px'));assert(css.includes('env(safe-area-inset-bottom)'));assert(!source.includes('FormData'));assert(!source.includes("'/api/rescue'"));});
  await test('stable_site_owner_keeps_receipt_after_wechat_canonical_binding',async()=>{const f=fixture(),s=f.session();f.ctx.state.user.account_user_id=f.ctx.state.user.user_id;s.receipts.write(s.owner,{client_request_id:'wc_original_submission',input_mode:'text',payload:{prompt:'私有'},draft:text(),state:'uncertain'});f.ctx.state.user.user_id='WX-3333333333333333';f.ctx.accountVersion++;assert(f.session().receipt());assert.equal(f.session().owner,'WEB-1111111111111111');});
  await test('cos_octet_stream_raw_image_is_normalized_without_server_proxy',async()=>{const f=fixture({fetch:async()=>({ok:true,status:200,blob:async()=>new Blob([new Uint8Array([255,216,255,0])],{type:'application/octet-stream'})})}),s=f.session();const blob=await s.original({orig_url:'https://cos.invalid/raw'});assert.equal(blob.type,'image/jpeg');});
  await test('real_dom_photo_selection_preview_template_fields_and_rights_gate',async()=>{
    const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom');const dom=new JSDOM('<main></main>',{url:'https://site.invalid'}),f=fixture();f.ctx.element=(tag,cls,text)=>{const el=dom.window.document.createElement(tag);el.className=cls||'';el.textContent=text||'';return el;};const view=dom.window.document.querySelector('main'),cleanup=await f.production.mountCreation(f.ctx,view,'create',{templateId:'poster'});await tick();
    const picker=view.querySelector('input[type=file]');Object.defineProperty(picker,'files',{value:[photo().blob],configurable:true});picker.dispatchEvent(new dom.window.Event('change',{bubbles:true}));await tick();assert(view.querySelector('img').src.startsWith('blob:'));assert.equal(view.querySelector('input[type=text]').value,'旅行');
    const submit=[...view.querySelectorAll('button')].find(el=>el.textContent==='开始生成');submit.click();await tick();assert(!f.calls.some(c=>c.url==='/api/rescue/by-upload'));assert(f.messages.some(m=>m.includes('使用权')));cleanup();dom.window.close();
  });
  await test('real_dom_exit_flushes_last_typed_description_before_debounce',async()=>{
    const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom');const dom=new JSDOM('<main></main>',{url:'https://site.invalid'}),f=fixture();f.ctx.element=(tag,cls,text)=>{const el=dom.window.document.createElement(tag);el.className=cls||'';el.textContent=text||'';return el;};const view=dom.window.document.querySelector('main'),cleanup=await f.production.mountCreation(f.ctx,view,'text');await tick();const textarea=view.querySelector('textarea');textarea.value='离开前的最后一句';textarea.dispatchEvent(new dom.window.Event('input',{bubbles:true}));cleanup();await tick();assert.equal((await f.ctx.creationOptions.drafts.read(f.ctx.state.user.user_id)).prompt,'离开前的最后一句');dom.window.close();
  });
  await test('cleanup_is_available_before_catalog_resolves_and_blocks_late_mount',async()=>{
    const f=fixture(),view=new Element('main');let finish;const base=f.ctx.api;f.ctx.api=(url,opts)=>url==='/api/templates'?new Promise(r=>finish=r):base(url,opts);
    const cleanup=await f.production.mountCreation(f.ctx,view,'create');cleanup();view.replaceChildren(new Element('h1','','新的页面'));finish(f.catalog);await tick();assert.equal(view.children[0].textContent,'新的页面');
  });
  await test('known_rejected_lookup_unblocks_with_actual_rejection_not_uncertain_message',async()=>{
    const f=fixture(),s=f.session();s.receipts.write(s.owner,{client_request_id:'wc_original_submission',input_mode:'text',payload:{prompt:'原始描述',expected_price:40},draft:text(),state:'uncertain'});const base=f.ctx.api;
    f.ctx.api=async(url,opts)=>url.startsWith('/api/me/submissions/')?{state:'rejected',detail:'价格未确认',http_status:409}:base(url,opts);
    const looked=await s.lookup();assert.equal(looked.state,'rejected');assert.equal(s.receipt(),null);assert(!f.calls.some(c=>c.url==='/api/text-generation'));
  });
  await test('legacy_result_and_comparison_are_repaired_via_json_then_cos_only',async()=>{
    const f=fixture(),s=f.session();const base=f.ctx.api;f.ctx.api=async(url,opts)=>{if(url.includes('/refresh-media?kind=')){f.calls.push({url,opts});return {url:'https://cos.invalid/'+url.split('kind=')[1]};}return base(url,opts);};
    assert.equal(await s.resultMedia('job','result','/api/images/legacy.jpg?expires=1&sig=old'),'https://cos.invalid/result');assert.equal(await s.resultMedia('job','orig','https://site.invalid/api/images/before.jpg?expires=1&sig=old'),'https://cos.invalid/orig');
    assert.equal(f.calls.filter(c=>c.url&&c.url.includes('/refresh-media')).length,2);assert(f.calls.filter(c=>c.url&&c.url.includes('/refresh-media')).every(c=>c.opts.method==='POST'));assert(!f.calls.some(c=>c.cos));
  });
  await test('repair_failure_never_falls_back_to_business_server_pixels',async()=>{
    const f=fixture(),s=f.session();f.ctx.api=async()=>({url:'/api/images/still-local.jpg'});await assert.rejects(s.resultMedia('job','result','/api/images/legacy.jpg'),/COS 直链/);assert(!f.calls.some(c=>c.cos));
  });
  await test('raw_recipe_original_is_not_repaired_through_comparison_endpoint',async()=>{
    const f=fixture(),s=f.session();await assert.rejects(s.original({complete:true,job_id:'job',orig_url:'/api/images/raw.jpg'}),/COS 直链/);assert(!f.calls.some(c=>c.url&&c.url.includes('/refresh-media')));assert(!f.calls.some(c=>c.cos));
  });
  await test('result_mount_repairs_both_legacy_sides_and_downloads_only_cos',async()=>{
    const f=fixture(),view=new Element('main'),base=f.ctx.api;f.ctx.api=async(url,opts)=>{if(url.includes('/refresh-media?kind=')){f.calls.push({url,opts});return {url:'https://cos.invalid/'+url.split('kind=')[1]};}if(url==='/api/jobs/legacy')return {status:'succeeded',input_mode:'photo',orig_url:'/api/images/before.jpg',result_url:'/api/images/after.jpg',width:100,height:100};return base(url,opts);};
    const cleanup=await f.production.mountCreation(f.ctx,view,'result',{jobId:'legacy'});await tick();await tick();const images=view.querySelectorAll('img');assert.equal(images.length,2);assert(images.every(image=>image.src.startsWith('https://cos.invalid/')));
    await view.querySelectorAll('button').find(b=>b.textContent==='下载图片').click();assert(f.calls.some(c=>c.cos==='https://cos.invalid/result'));assert(!f.calls.some(c=>c.cos&&c.cos.includes('/api/images/')));cleanup();
  });
  await test('login_completed_after_cleanup_never_navigates_or_submits_from_old_mount',async()=>{
    const f=fixture({guest:true}),view=new Element('main');let finish;f.ctx.requireLogin=()=>new Promise(r=>finish=r);
    const cleanup=await f.production.mountCreation(f.ctx,view,'text',{initialDraft:text()});await tick();const click=view.querySelectorAll('button').find(b=>b.textContent==='开始生成').click();await tick();
    cleanup();f.ctx.accountVersion++;f.ctx.state.user={user_id:'WEB-1111111111111111',account_user_id:'WEB-1111111111111111',balance:0};finish(true);await click;
    assert.equal(f.navigation.length,0);assert(!f.calls.some(c=>c.url==='/api/text-generation'||c.url==='/api/rescue/by-upload'));
  });
  await test('real_dom_guest_photo_has_discoverable_text_entry_without_fake_account_balance',async()=>{
    const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom'),dom=new JSDOM('<main></main>',{url:'https://site.invalid'}),f=fixture({guest:true});f.ctx.element=(tag,cls,text)=>{const el=dom.window.document.createElement(tag);el.className=cls||'';el.textContent=text||'';return el;};
    const view=dom.window.document.querySelector('main'),cleanup=await f.production.mountCreation(f.ctx,view,'create');await tick();assert(view.classList.contains('creation-form-page'));const entry=view.querySelector('[data-action="mode-text"]');assert(entry);assert.equal(entry.textContent,'文字生图');assert(!entry.disabled);assert(view.querySelector('.creation-submit-bar').textContent.includes('注册后创作'));assert(!view.querySelector('.creation-submit-bar').textContent.includes('余额 0'));
    entry.click();await tick();assert.equal(f.navigation[0].route,'text');assert(!f.calls.some(c=>c.url==='/api/text-generation'||c.url==='/api/rescue/by-upload'));cleanup();dom.window.close();
  });
  await test('real_dom_text_to_photo_switch_preserves_draft_and_shows_real_zero_balance',async()=>{
    const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom'),dom=new JSDOM('<main></main>',{url:'https://site.invalid'}),f=fixture();f.ctx.state.user.balance=0;f.ctx.element=(tag,cls,text)=>{const el=dom.window.document.createElement(tag);el.className=cls||'';el.textContent=text||'';return el;};
    const view=dom.window.document.querySelector('main'),cleanup=await f.production.mountCreation(f.ctx,view,'text');await tick();const description=view.querySelector('textarea');description.value='切换后仍保留的描述';description.dispatchEvent(new dom.window.Event('input',{bubbles:true}));assert(view.querySelector('.creation-submit-bar').textContent.includes('余额 0 光子'));
    view.querySelector('[data-action="mode-photo"]').click();await tick();assert.equal(f.navigation[0].route,'create');assert.equal(f.navigation[0].params.modeDrafts.text.prompt,'切换后仍保留的描述');assert.equal((await f.ctx.creationOptions.drafts.read(f.ctx.state.user.user_id)).prompt,'切换后仍保留的描述');assert(!f.calls.some(c=>c.url==='/api/text-generation'));cleanup();dom.window.close();
  });
  await test('real_dom_unconfigured_text_still_has_both_navigation_entries_but_never_submits',async()=>{
    const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom'),dom=new JSDOM('<main></main>',{url:'https://site.invalid'}),f=fixture({guest:true});f.config.text_generation.ready=false;f.ctx.element=(tag,cls,text)=>{const el=dom.window.document.createElement(tag);el.className=cls||'';el.textContent=text||'';return el;};
    const view=dom.window.document.querySelector('main'),cleanup=await f.production.mountCreation(f.ctx,view,'text');await tick();assert(view.querySelector('[data-action="mode-text"]'));assert(view.querySelector('[data-action="mode-photo"]'));assert(view.textContent.includes('文字生图暂未开放'));const submit=[...view.querySelectorAll('button')].find(b=>b.textContent==='开始生成');assert(submit.disabled);submit.click();await tick();assert(!f.calls.some(c=>c.url==='/api/text-generation'));view.querySelector('[data-action="mode-photo"]').click();await tick();assert.equal(f.navigation[0].route,'create');cleanup();dom.window.close();
  });
  await test('real_cssom_mobile_cta_is_fixed_and_reserves_flow_space_desktop_stays_sticky',()=>{
    const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom'),css=fs.readFileSync(path.join(root,'backend/static/web/creation.css'),'utf8'),dom=new JSDOM('<style>'+css+'</style><main></main>');
    const rules=[...dom.window.document.styleSheets[0].cssRules],container=rules.find(rule=>rule.selectorText==='.creation-module');assert.equal(container.style.getPropertyValue('max-width'),'1120px');assert.equal(container.style.getPropertyValue('padding'),'28px 20px 80px');
    const mobile=rules.find(rule=>rule.conditionText&&rule.conditionText.includes('700px')),bar=[...mobile.cssRules].find(rule=>rule.selectorText==='.creation-form-page .creation-submit-bar');assert.equal(bar.style.getPropertyValue('position'),'fixed');assert.equal(bar.style.getPropertyValue('bottom'),'calc(76px + env(safe-area-inset-bottom))');assert.equal(bar.style.getPropertyValue('left'),'18px');assert.equal(bar.style.getPropertyValue('right'),'18px');assert.equal(bar.style.getPropertyValue('z-index'),'50');assert.equal([...mobile.cssRules].find(rule=>rule.selectorText==='.creation-form-page').style.getPropertyValue('padding-bottom'),'calc(230px + env(safe-area-inset-bottom))');assert.equal(rules.find(rule=>rule.selectorText==='.creation-submit-bar').style.getPropertyValue('position'),'sticky');dom.window.close();
  });
  fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'web_creation_results.json'),JSON.stringify({cases:rows},null,2));const failed=rows.filter(r=>!r.passed).length;console.log(`WEB_CREATION_SUMMARY total=${rows.length} passed=${rows.length-failed} failed=${failed}`);process.exitCode=failed?1:0;
})();
