/* Production ESM consumes server category DTOs; legacy servers stay readable. */
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom'),root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/dynamic-community-ui')),cases=[];
const tick=async()=>{for(let i=0;i<10;i++)await new Promise(r=>setImmediate(r));};
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name)}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name,e)}}
(async()=>{
 const {mountLibrary}=await import(pathToFileURL(path.join(root,'backend/static/web/library.js')).href);
 function fixture(api){const dom=new JSDOM('<main></main>',{url:'https://site.invalid',pretendToBeVisual:true}),doc=dom.window.document,calls=[];const ctx={state:{user:{user_id:'A'}},accountVersion:1,document:doc,element:(tag,cls,text)=>{const n=doc.createElement(tag);n.className=cls||'';if(text!=null)n.textContent=text;return n},requireLogin:async()=>true,toast(){},navigate(){},confirm:async()=>true,api:async(url,options)=>{calls.push({url,options});return api(url,options)}};return {dom,doc,ctx,calls}}
 await test('community_nav_uses_enabled_template_groups_from_feed_and_not_legacy_labels',async()=>{const f=fixture(()=>({enabled:true,items:[],total:0,next_offset:0,has_more:false,categories:[{id:'restore',name:'修复增强'},{id:'g_travel',name:'旅行创意'}]}));const stop=await mountLibrary(f.ctx,f.doc.querySelector('main'),'community');await tick();const filters=f.doc.querySelectorAll('.lib-filter'),text=[...filters].map(n=>n.textContent);assert(text.includes('修复增强'));assert(text.includes('旅行创意'));assert(!text.includes('复古胶片'));[...filters].find(n=>n.textContent==='旅行创意').click();await tick();assert(f.calls.some(x=>x.url.includes('category=g_travel')));stop();f.dom.window.close()});
 await test('post_edit_picker_uses_owner_categories_and_preserves_old_category',async()=>{const f=fixture(url=>url.includes('/api/jobs/')?{id:'job1',status:'succeeded',result_url:'https://cos.invalid/result',orig_url:''}:{items:[],total:0,has_more:false,categories:[{id:'g_travel',name:'旅行创意'}]});const stop=await mountLibrary(f.ctx,f.doc.querySelector('main'),'submit',{jobId:'job1',preset:{category:'old_removed'}});await tick();const select=f.doc.querySelector('[aria-label="投稿展区"]');assert(select);assert.equal(select.value,'old_removed');assert([...select.options].some(x=>x.value==='all'&&x.textContent==='按模板自动分组'));assert([...select.options].some(x=>x.value==='g_travel'));assert([...select.options].some(x=>x.value==='old_removed'));assert(f.calls.some(x=>x.url.includes('/submissions/mine?limit=1')));stop();f.dom.window.close()});
 await test('empty_categories_keep_all_and_liked_routes_without_inventing_hidden_groups',async()=>{const f=fixture(()=>({enabled:true,items:[],has_more:false,next_offset:0,categories:[]}));const stop=await mountLibrary(f.ctx,f.doc.querySelector('main'),'community');await tick();assert.equal(f.doc.querySelectorAll('.lib-filter').length,2);assert(f.doc.body.textContent.includes('全部展品'));assert(f.doc.body.textContent.includes('我喜欢的'));stop();f.dom.window.close()});
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'dynamic_community_frontend_results.json'),JSON.stringify({cases},null,2),'utf8');const passed=cases.filter(x=>x.passed).length;console.log(`DYNAMIC_COMMUNITY_FRONTEND_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1});
