/* Homepage-only UI contracts; real handlers execute with wx navigation doubles. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/home-shortcuts')),cases=[];
const read=ext=>fs.readFileSync(path.join(root,'miniprogram/pages/index/index.'+ext),'utf8'),xml=read('wxml'),css=read('wxss');
function rule(selector){let value={};for(const block of css.matchAll(/([^{}]+)\{([^{}]*)\}/g))if(block[1].trim()===selector)for(const property of block[2].matchAll(/([a-z-]+)\s*:\s*([^;]+)(?:;|$)/g))value[property[1]]=property[2].trim();return value;}
function fixture(){let p;const routes=[],history=[{jobId:'existing',status:'succeeded'}],template={id:'selected'},app={globalData:{historyList:history,selectedTemplate:template}};let picked=0,requests=0;
 vm.runInNewContext(read('js'),{Page:x=>p=x,getApp:()=>app,require:n=>n.includes('creation-draft')?{}:{request(){requests++;}},wx:{navigateTo:x=>routes.push(x.url),chooseMedia(){picked++;}},console,setTimeout,clearTimeout,Date});p.data=JSON.parse(JSON.stringify(p.data));p.setData=x=>Object.assign(p.data,x);return{p,app,history,template,routes,picked:()=>picked,requests:()=>requests};}
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name);}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name,e);}}
(async()=>{
 await test('two_shortcuts_immediately_follow_photo_button_with_both_hints_below',()=>{const start=xml.indexOf('class="upload-portal'),end=xml.indexOf('class="generation-warning"'),part=xml.slice(start,end);assert(/<view class="portal-btn">[\s\S]*?<\/view>\s*<view class="home-quick-actions">/.test(part));const actions=part.indexOf('home-quick-actions');assert(actions<part.indexOf('portal-desc'));assert(part.indexOf('portal-desc')<part.indexOf('portal-specs'));assert(part.indexOf('home-work-action')<part.indexOf('portal-desc'));assert.equal((part.match(/<button /g)||[]).length,2);assert.equal((xml.match(/home-quick-actions/g)||[]).length,1);assert(xml.indexOf('home-quick-actions')<xml.indexOf('showcase-section'));assert.equal(rule('.home-quick-actions')['margin-top'],'0');});
 await test('secondary_taps_catch_bubbling_while_parent_photo_action_remains_bound',()=>{assert(/class="upload-portal[^\"]*" bindtap="onPickImage"/.test(xml));assert(/<button class="home-quick-action home-text-action" catchtap="onOpenTextGeneration"/.test(xml));assert(/<button class="home-quick-action home-work-action" catchtap="onOpenHistory"/.test(xml));assert(!xml.includes('bindtap="onOpenHistory"'));assert(!xml.includes('bindtap="onOpenTextGeneration"'));});
 await test('equal_square_centered_secondary_buttons_reset_native_margins_and_after_border',()=>{const s=rule('.home-quick-action'),group=rule('.home-quick-actions');assert.equal(group.display,'flex');assert.equal(group.width,'100%');assert.equal(s.flex,'1 1 0');assert.equal(s['min-width'],'0');assert.equal(s.height,'88rpx');assert.equal(s['min-height'],'88rpx');assert.equal(s.margin,'0');assert.equal(s['border-radius'],'0');assert.equal(s['align-items'],'center');assert.equal(s['justify-content'],'center');assert.equal(rule('.home-quick-action::after').border,'none');assert(s.background.includes('--paper-card-subtle'));});
 await test('my_works_is_available_when_empty_count_is_only_a_positive_child_label',()=>{const open=/<button class="home-quick-action home-work-action"([^>]*)>/.exec(xml);assert(open);assert(!open[1].includes('wx:if'));assert(xml.includes('我的作品<text wx:if="{{ historyCount > 0 }}">（{{ historyCount }}）</text>'));const f=fixture();assert.equal(f.p.data.historyCount,0);f.p.onOpenHistory();assert.equal(f.routes[0],'/pages/works/works');});
 await test('navigation_uses_original_routes_without_choosing_photo_requests_or_resetting_carried_style',()=>{const f=fixture();f.p.data.activeTemplate=f.template;f.p.data.historyCount=12;f.p.onOpenTextGeneration();f.p.onOpenHistory();assert.deepEqual(f.routes,['/pages/text-generation/text-generation','/pages/works/works']);assert.equal(f.picked(),0);assert.equal(f.requests(),0);assert.strictEqual(f.p.data.activeTemplate,f.template);assert.strictEqual(f.app.globalData.historyList,f.history);assert.equal(f.p.data.historyCount,12);});
 await test('oversized_count_cannot_push_arrow_outside_single_line_label',()=>{const s=rule('.quick-action-label');assert.equal(s.display,'block');assert.equal(s['min-width'],'0');assert.equal(s.overflow,'hidden');assert.equal(s['text-overflow'],'ellipsis');assert.equal(s['white-space'],'nowrap');assert.equal(rule('.quick-action-arrow')['flex-shrink'],'0');});
 await test('black_photo_action_and_horizontal_hot_six_gallery_keep_their_existing_geometry',()=>{assert.equal(rule('.portal-btn').height,'96rpx');assert(xml.includes('<scroll-view class="showcase-scroll" scroll-x'));assert.equal(rule('.showcase-card').width,'280rpx');assert.equal(rule('.showcase-card').height,'540rpx');assert.equal(rule('.showcase-cover-wrap').height,'320rpx');assert(xml.includes('热门风格'));});
 await test('obsolete_bottom_links_and_styles_are_removed_with_no_duplicate_targets',()=>{assert(!xml.includes('text-generation-entry'));assert(!xml.includes('history-entry'));assert(!xml.includes('查看过往修复记录'));assert(!css.includes('.history-entry'));assert(!css.includes('.text-generation-entry'));assert.equal((xml.match(/catchtap="onOpenTextGeneration"/g)||[]).length,1);assert.equal((xml.match(/catchtap="onOpenHistory"/g)||[]).length,1);});
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'mini_home_shortcuts_results.json'),JSON.stringify({cases},null,2),'utf8');const passed=cases.filter(x=>x.passed).length;console.log(`MINI_HOME_SHORTCUTS_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1});
