/* Real production ESM + jsdom, synthetic metadata/COS only. */
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom'),root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/template-share-web'));
const tick=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};const cases=[];
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name);}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
const clone=x=>JSON.parse(JSON.stringify(x));
(async()=>{
 const {TemplateSharingClient,mountTemplateSharing,sharingContent,signedUploadUrl,templateUploadHeaders,GUIDE_PROMPT}=await import(pathToFileURL(path.join(root,'backend/static/web/template-sharing.js')).href);
 const {CreationSession,mountCreation}=await import(pathToFileURL(path.join(root,'backend/static/web/creation.js')).href);
 function fixture({guest=false,api,fetch}={}){
  const dom=new JSDOM('<main></main>',{url:'https://site.invalid/',pretendToBeVisual:true}),doc=dom.window.document,calls=[],puts=[],nav=[],toasts=[];
  let record={id:'share_1',revision:1,status:'draft',name:'风格',subtitle:'',prompt:'水彩风格',guide:{advice:'',suitable:[],unsuitable:[],tips:[]},covers:[],cover_tokens:[],has_published:false,published_revision:0};let serial=0;
  const ctx={accountVersion:1,state:{user:guest?null:{user_id:'CANONICAL',account_user_id:'SITE'},config:{prices:{light:40,fine:80},text_generation:{price:40}}},document:doc,requireLogin:async()=>!guest,navigate:(r,p)=>nav.push({r,p}),toast:t=>toasts.push(t),confirm:async()=>true,element:(tag,cls,text)=>{const n=doc.createElement(tag);n.className=cls||'';if(text!=null)n.textContent=text;return n;},api:async(url,settings={})=>{
   calls.push({url,settings});if(api)return api(url,settings,record);
   if(url.includes('/mine?'))return {items:[clone(record)],total:1,next_offset:1,has_more:false,rewards:{reward_earned:80,reward_credited:40,reward_offset:40,recovery_due:20}};
   if(url.endsWith('/uploads'))return {upload_token:'upload_'+(++serial),url:'https://cos.invalid/upload'+serial+'?sig=fixture',headers:{'Content-Type':'image/png','x-cos-acl':'private'}};
   if(url.includes('/complete')){const cover={token:url.split('/').at(-2),preview_url:'https://cos.invalid/full'+serial,thumbnail_url:'https://cos.invalid/small'+serial,width:100,height:100};record.covers.push(cover);record.cover_tokens.push(cover.token);return {submission:clone(record),cover};}
   if(url.endsWith('/withdraw'))record={...record,status:'withdrawn',revision:record.revision+1,has_published:false};
   if(settings.method==='PUT')record={...record,...settings.data,status:settings.data.submit?'pending':'draft',revision:record.revision+1};
   return {submission:clone(record)};
  }};
  const options={fetch:async(url,settings)=>{puts.push({url,settings});return fetch?fetch(url,settings):{ok:true};},storage:dom.window.localStorage};ctx.templateSharingOptions=options;
  return {ctx,doc,dom,calls,puts,nav,toasts,record,client:()=>new TemplateSharingClient(ctx,options),close:()=>dom.window.close()};
 }
 await test('user_content_drops_every_runtime_identity_group_and_reward_field',()=>{const value=sharingContent({name:'模板',prompt:'风格',engine:'fine',model_override:'bad',source:'official',price:0,group_id:'new',reward:999,author_name:'other',guide:{suitable:' 清晰人像\n全身 '}});assert.deepEqual(Object.keys(value),['name','subtitle','prompt','guide']);assert.deepEqual(value.guide.suitable,['清晰人像','全身']);});
 await test('guest_routes_never_request_owner_data_or_create_visitors',async()=>{const f=fixture({guest:true});const stop=await mountTemplateSharing(f.ctx,f.doc.querySelector('main'),'template-shares');assert.equal(f.calls.length,0);stop();f.close();});
 await test('three_covers_use_signed_cos_put_without_auth_then_metadata_submit',async()=>{const f=fixture(),c=f.client();const covers=[];for(let i=0;i<3;i++)covers.push(await c.upload(new f.dom.window.File(['pixels'],'cover.png',{type:'image/png'})));await c.save({name:'模板',prompt:'画面风格',engine:'fine'},covers.map(x=>x.token),true);assert.equal(f.puts.length,3);assert(f.puts.every(p=>p.settings.method==='PUT'&&p.settings.credentials==='omit'&&!p.settings.headers.Authorization));const put=f.calls.find(x=>x.settings.method==='PUT');assert.deepEqual(put.settings.data.cover_tokens,['upload_1','upload_2','upload_3']);assert.equal(put.settings.data.submit,true);assert(!f.calls.some(x=>/rescue|text-generation/.test(x.url)));c.close();f.close();});
 await test('lost_draft_response_reuses_durable_request_id_without_duplicate_identity',async()=>{let lost=true;const f=fixture({api:async(url,settings,row)=>{if(lost){lost=false;throw new Error('offline');}return {submission:clone(row)};}}),first=f.client();await assert.rejects(first.ensure());const id=JSON.parse(f.dom.window.localStorage.getItem(first.key)).request_id;first.close();const next=f.client();await next.ensure();assert.equal(f.calls[0].settings.data.request_id,id);assert.equal(f.calls[1].settings.data.request_id,id);next.close();f.close();});
 await test('account_change_discards_late_upload_ticket_and_no_cross_account_put',async()=>{let finish;const f=fixture(),c=f.client();await c.ensure();const base=f.ctx.api;f.ctx.api=(url,settings)=>url.endsWith('/uploads')?new Promise(r=>finish=r):base(url,settings);const pending=c.upload(new f.dom.window.File(['x'],'cover.png',{type:'image/png'}));await tick();f.ctx.accountVersion++;f.ctx.state.user={user_id:'OTHER'};finish({upload_token:'old',url:'https://cos.invalid/old'});await assert.rejects(pending,e=>e.code==='INACTIVE');assert.equal(f.puts.length,0);c.close();f.close();});
 await test('unsafe_ticket_urls_and_four_cover_submissions_are_rejected',async()=>{assert.throws(()=>signedUploadUrl('/api/upload','https://site.invalid'));assert.throws(()=>signedUploadUrl('https://site.invalid/pixels','https://site.invalid'));const f=fixture(),c=f.client();await assert.rejects(c.save({name:'模板',prompt:'风格'},['a','b','c','d'],true));assert.equal(f.calls.length,0);c.close();f.close();});
 await test('approved_revision_edit_retains_old_public_version_and_posts_revision',async()=>{const f=fixture(),c=f.client();f.record.status='approved';f.record.has_published=true;f.record.published_revision=1;await c.load('share_1');await c.save({name:'新版',prompt:'改版'},['cover'],true);const req=f.calls.at(-1);assert.equal(req.settings.data.revision,1);assert.equal(c.current.has_published,true);assert.equal(c.current.published_revision,1);assert.equal(c.current.status,'pending');c.close();f.close();});
 await test('owner_form_has_four_guides_manual_ai_copy_and_no_runtime_controls',async()=>{const f=fixture(),stop=await mountTemplateSharing(f.ctx,f.doc.querySelector('main'),'template-share',{fresh:true});await tick();const text=f.doc.body.textContent;assert(text.includes('AI整理指南'));for(const name of ['advice','suitable','unsuitable','tips'])assert(f.doc.querySelector('[name="'+name+'"]'));for(const name of ['engine','model_override','price','group_id','source','reward'])assert(!f.doc.querySelector('[name="'+name+'"]'));assert(GUIDE_PROMPT.includes('不要编造'));stop();f.close();});
 await test('form_uploads_all_three_selected_files_without_skipping_array_entries',async()=>{const f=fixture(),stop=await mountTemplateSharing(f.ctx,f.doc.querySelector('main'),'template-share',{fresh:true});f.doc.querySelector('[name="name"]').value='模板';f.doc.querySelector('[name="prompt"]').value='画面';f.doc.querySelector('[name="consent"]').checked=true;const picker=f.doc.querySelector('[name="files"]');Object.defineProperty(picker,'files',{value:[1,2,3].map(i=>new f.dom.window.File(['pixels'],'cover'+i+'.png',{type:'image/png'}))});picker.dispatchEvent(new f.dom.window.Event('change'));f.doc.querySelector('form').dispatchEvent(new f.dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(f.puts.length,3);assert.equal(f.calls.filter(x=>x.settings.method==='PUT').length,1);assert(f.calls.find(x=>x.settings.method==='PUT').settings.data.consent);assert(f.doc.body.textContent.includes('已提交审核'));assert.equal(f.doc.querySelector('[name="consent"]').checked,false);stop();f.close();});
 await test('unchecked_consent_blocks_every_upload_and_submission',async()=>{const f=fixture(),stop=await mountTemplateSharing(f.ctx,f.doc.querySelector('main'),'template-share',{fresh:true});f.doc.querySelector('[name="name"]').value='模板';f.doc.querySelector('[name="prompt"]').value='画面';f.doc.querySelector('form').dispatchEvent(new f.dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(f.calls.length,0);assert.equal(f.puts.length,0);assert(f.doc.body.textContent.includes('请先确认本次分享授权'));stop();f.close();});
 await test('empty_draft_is_allowed_and_rewards_summary_never_changes_balance',async()=>{const f=fixture(),c=f.client();await c.save({name:'',prompt:''},[],false);assert.equal(f.calls.at(-1).settings.data.consent,false);const stop=await mountTemplateSharing(f.ctx,f.doc.querySelector('main'),'template-shares');await tick();assert(f.doc.body.textContent.includes('已产生 80'));assert(f.doc.body.textContent.includes('已到账 40'));assert(f.doc.body.textContent.includes('不扣已有余额'));assert(!('balance' in f.ctx.state.user));stop();c.close();f.close();});
 await test('catalog_hot_latest_random_and_normal_category_server_sort_are_distinct',()=>{const f=fixture(),s=new CreationSession(f.ctx,{receipts:{},drafts:{}});s.templates=[{id:'a',group_id:'art',sort:1,usage_count:1,published_at:10},{id:'b',group_id:'art',sort:2,usage_count:99,published_at:20},{id:'user',group_id:'',source:'user',sort:0,usage_count:50,published_at:30}];assert.equal(s.filter()[0].id,'b');assert.equal(s.filter('','all','all','latest')[0].id,'user');assert.equal(s.filter('','art')[0].id,'a');assert.deepEqual(s.filter('','all','all','random',new Map([['a',3],['b',2],['user',1]])).map(x=>x.id),['user','b','a']);s.close();f.close();});
 await test('my_templates_edit_route_and_withdraw_are_owner_scoped',async()=>{const f=fixture(),stop=await mountTemplateSharing(f.ctx,f.doc.querySelector('main'),'template-shares');await tick();f.doc.querySelectorAll('button')[2].click();await tick();assert(f.nav.some(x=>x.r==='template-share'&&x.p.id==='share_1'));const c=f.client();await c.load('share_1');await c.withdraw();assert.equal(f.calls.at(-1).settings.data.revision,1);stop();c.close();f.close();});
 await test('real_catalog_badges_sort_select_and_existing_categories_do_not_add_user_groups',async()=>{const f=fixture(),base=f.ctx.api;f.ctx.api=async(url,settings)=>url==='/api/templates'?{groups:[{id:'art',name:'艺术'}],items:[{id:'official',name:'官方样例',source:'official',group_id:'art',sort:1,usage_count:10,published_at:1,cover:'https://cos.invalid/a'},{id:'user',name:'用户样例',source:'user',author_name:'作者',group_id:'',sort:0,usage_count:1,published_at:2,cover:'https://cos.invalid/b'}]}:url==='/api/me/preferences'?{}:base(url,settings);const stop=await mountCreation(f.ctx,f.doc.querySelector('main'),'templates');await tick();assert.equal(f.doc.querySelectorAll('.creation-source-badge').length,2);assert(f.doc.body.textContent.includes('官方'));assert(f.doc.body.textContent.includes('用户分享'));assert(!f.doc.querySelector('[aria-label="模板分类"]').textContent.includes('用户分享'));const sorting=f.doc.querySelector('[aria-label="模板排序"]');assert.equal(sorting.value,'hot');sorting.value='latest';sorting.dispatchEvent(new f.dom.window.Event('change'));assert(f.doc.querySelector('.creation-template-card').textContent.includes('用户样例'));const category=f.doc.querySelector('[aria-label="模板分类"]');category.value='art';category.dispatchEvent(new f.dom.window.Event('change'));assert.equal(f.doc.querySelectorAll('.creation-template-card').length,1);assert(f.doc.querySelector('[aria-label="模板排序"]').disabled);stop();f.close();});
 await test('oversized_eight_mebibyte_cover_is_rejected_before_ticket',async()=>{const f=fixture(),c=f.client();await assert.rejects(c.upload({type:'image/png',size:8*1024*1024+1}),/8MB/);assert.equal(f.calls.length,0);c.close();f.close();});
 await test('late_owner_load_cannot_repaint_after_cleanup_or_send_follow_up_mutations',async()=>{let finish;const f=fixture({api:()=>new Promise(resolve=>finish=resolve)});const view=f.doc.querySelector('main'),stop=await mountTemplateSharing(f.ctx,view,'template-share',{id:'share_1'});stop();view.replaceChildren(f.doc.createTextNode('新的页面'));finish({submission:{...f.record,name:'旧响应'}});await tick();assert.equal(view.textContent,'新的页面');assert.equal(f.calls.length,1);f.close();});
 await test('signed_put_headers_are_case_normalized_private_and_do_not_leak_site_credentials',()=>{const headers=templateUploadHeaders({'Content-Type':'image/png','content-type':'image/png','x-cos-acl':'private'},'image/png');assert.deepEqual(headers,{'content-type':'image/png','x-cos-acl':'private'});assert.throws(()=>templateUploadHeaders({Authorization:'Bearer site'},'image/png'));assert.throws(()=>templateUploadHeaders({Cookie:'session'},'image/png'));assert.throws(()=>templateUploadHeaders({'Content-Type':'image/jpeg'},'image/png'));});
 await test('saving_private_draft_uploads_without_publication_consent_or_paid_post',async()=>{const f=fixture(),stop=await mountTemplateSharing(f.ctx,f.doc.querySelector('main'),'template-share',{fresh:true});const picker=f.doc.querySelector('[name="files"]');Object.defineProperty(picker,'files',{value:[new f.dom.window.File(['pixels'],'cover.png',{type:'image/png'})]});picker.dispatchEvent(new f.dom.window.Event('change'));const save=Array.from(f.doc.querySelectorAll('button')).find(b=>b.textContent==='保存草稿');save.click();await tick();assert.equal(f.puts.length,1);assert.equal(f.puts[0].settings.headers['x-cos-acl'],'private');const req=f.calls.find(x=>x.settings.method==='PUT');assert.equal(req.settings.data.submit,false);assert.equal(req.settings.data.consent,false);assert.equal(f.doc.querySelector('[name="consent"]').checked,false);stop();f.close();});
 await test('random_catalog_order_stays_stable_until_explicit_shuffle_without_api_or_post',async()=>{const f=fixture(),base=f.ctx.api;f.ctx.api=async(url,settings)=>url==='/api/templates'?{groups:[],items:[{id:'a',name:'A',usage_count:2},{id:'b',name:'B',usage_count:1}]}:url==='/api/me/preferences'?{}:base(url,settings);const stop=await mountCreation(f.ctx,f.doc.querySelector('main'),'templates');await tick();const original=Math.random;let values=[0.9,0.1,0.1,0.9];Math.random=()=>values.shift();try{const sorting=f.doc.querySelector('[aria-label="模板排序"]');sorting.value='random';sorting.dispatchEvent(new f.dom.window.Event('change'));const names=()=>Array.from(f.doc.querySelectorAll('.creation-template-card h3')).map(n=>n.textContent);assert.deepEqual(names(),['B','A']);f.doc.querySelector('[aria-label="搜索风格"]').dispatchEvent(new f.dom.window.Event('input'));assert.deepEqual(names(),['B','A']);const shuffle=Array.from(f.doc.querySelectorAll('button')).find(b=>b.textContent==='换一批');assert(!shuffle.hidden);shuffle.click();assert.deepEqual(names(),['A','B']);assert.equal(f.calls.length,0);}finally{Math.random=original;stop();f.close();}});
 await test('pending_editor_is_read_only_until_withdraw_without_disabling_withdraw_action',async()=>{const f=fixture();f.record.status='pending';f.record.covers=[{token:'old',preview_url:'https://cos.invalid/full'}];const stop=await mountTemplateSharing(f.ctx,f.doc.querySelector('main'),'template-share',{id:'share_1'});await tick();assert(f.doc.body.textContent.includes('审核中暂不可编辑'));assert(Array.from(f.doc.querySelectorAll('form input,form textarea,form button')).every(n=>n.disabled));assert(f.doc.querySelector('.template-share-covers button').disabled);const withdraw=Array.from(f.doc.querySelectorAll('button')).find(b=>b.textContent==='撤回此模板');assert(!withdraw.disabled);withdraw.click();await tick();assert(!f.doc.querySelector('[name="name"]').disabled);assert.equal(f.calls.at(-1).settings.data.revision,1);stop();f.close();});
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'template_share_web_results.json'),JSON.stringify({summary:{total:cases.length,passed:cases.filter(x=>x.passed).length,failed:cases.filter(x=>!x.passed).length},cases},null,2));const passed=cases.filter(x=>x.passed).length;console.log(`TEMPLATE_SHARE_WEB_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1;});
