/* Preserve community posting after ordinary Works no longer exposes a post button. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/community-work-picker')),cases=[];
function fixture(handler){let p;const calls=[],api={absolute:x=>x||'',request:async(url,options)=>{calls.push({url,options});return handler(url,options)}};vm.runInNewContext(fs.readFileSync(path.join(root,'miniprogram/pages/community-submit/community-submit.js'),'utf8'),{Page:x=>p=x,require:()=>api,getApp:()=>({globalData:{}}),wx:{showToast(){},navigateTo(){},switchTab(){}},console,setTimeout,clearTimeout,Date});p.data=JSON.parse(JSON.stringify(p.data));p.setData=x=>Object.assign(p.data,x);return {p,calls};}
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name)}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name,e)}}
(async()=>{
 await test('community_chooses_owned_finished_work_directly_without_works_submission_entry',async()=>{const job={id:'job_fixture1',status:'succeeded',result_url:'https://cos.invalid/hd',thumb_url:'https://cos.invalid/small',template_name:'胶片'},f=fixture(url=>url.startsWith('/api/my/jobs')?{jobs:[job],has_more:false,next_offset:1}:job);f.p.data.consent=true;await f.p.onChooseWork();assert.equal(f.p.data.showWorkPicker,true);assert.equal(f.p.data.workChoices[0].preview,job.thumb_url);await f.p.onSelectWork({currentTarget:{dataset:{id:job.id}}});assert.equal(f.p.data.showWorkPicker,false);assert.equal(f.p.data.jobId,job.id);assert.equal(f.p.data.consent,false);assert(f.calls[0].url.includes('status=succeeded'));assert.equal(f.calls[1].url,'/api/jobs/'+job.id);assert(f.calls.every(x=>!x.options||x.options.method!=='POST'));assert(fs.readFileSync(path.join(root,'miniprogram/pages/community/community.js'),'utf8').includes("onContribute(){wx.navigateTo({url:'/pages/community-submit/community-submit'})"))});
 await test('picker_paginates_recent_finished_jobs_by_exact_next_offset_and_filters_unfinished',async()=>{let more=false;const f=fixture(()=>({jobs:more?[{id:'b',status:'succeeded',result_url:'https://cos.invalid/b'}]:[{id:'a',status:'succeeded',result_url:'https://cos.invalid/a'},{id:'bad',status:'processing',result_url:'https://cos.invalid/bad'}],has_more:!more,next_offset:24}));await f.p.onChooseWork();assert.equal(f.p.data.workChoices.length,1);more=true;await f.p.onMoreWorkChoices();assert.equal(f.p.data.workChoices.length,2);assert(f.calls[1].url.includes('offset=24'))});
 await test('closed_picker_late_private_response_cannot_restore_modal_or_stale_rows',async()=>{let resolve;const f=fixture(()=>new Promise(r=>resolve=r));const pending=f.p.onChooseWork();f.p.onCloseWorkPicker();resolve({jobs:[{id:'secret',status:'succeeded',result_url:'https://cos.invalid/a'}]});await pending;assert.equal(f.p.data.workChoices.length,0);assert.equal(f.p.data.showWorkPicker,false)});
 await test('picker_rejects_nonadvancing_or_noninteger_cursor_and_preserves_previous_page',async()=>{let response={jobs:[{id:'a',status:'succeeded',result_url:'https://cos.invalid/a'}],has_more:true,next_offset:24};const f=fixture(()=>response);await f.p.onChooseWork();for(const next_offset of [0,24,23,-1,24.5,undefined]){response={jobs:[{id:'bad',status:'succeeded',result_url:'https://cos.invalid/bad'}],has_more:true,next_offset};await f.p.onMoreWorkChoices();assert.equal(f.p.data.workChoices.map(x=>x.id).join(','),'a');assert.equal(f.p._workNextOffset,24);assert(f.p.data.workPickerError.includes('分页信息异常'));assert.equal(f.p.data.workPickerLoading,false);}response={jobs:[{id:'b',status:'succeeded',result_url:'https://cos.invalid/b'}],has_more:false,next_offset:25};await f.p.onMoreWorkChoices();assert.equal(f.p.data.workChoices.map(x=>x.id).join(','),'a,b');assert.equal(f.p.data.workPickerError,'')});
 await test('posting_picker_reads_categories_from_existing_owner_mine_response_without_extra_get',async()=>{const f=fixture(()=>({items:[],has_more:false,next_offset:0,categories:[{id:'restore',name:'修复增强'},{id:'g_travel',name:'旅行创意'}]}));await f.p.loadMine();assert.equal(f.p.data.categories.map(x=>x.id).join(','),'all,restore,g_travel');assert.equal(f.p.data.categories[0].name,'按模板自动分组');assert.equal(f.calls.length,1);assert(f.calls[0].url.includes('/submissions/mine'))});
 await test('old_post_category_is_preserved_for_revision_edit_not_silently_relabelled',async()=>{const f=fixture(()=>({items:[],next_offset:0,has_more:false,categories:[{id:'restore',name:'修复增强'}]}));f.p.setData({categories:[{id:'all',name:'未分组'},{id:'old_removed',name:'旧分类'}],categoryIndex:1});await f.p.loadMine();assert.equal(f.p.data.categories[f.p.data.categoryIndex].id,'old_removed');assert.equal(f.p.categoryIndexFor('film'),2+1)});
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'community_work_picker_results.json'),JSON.stringify({cases},null,2),'utf8');const passed=cases.filter(x=>x.passed).length;console.log(`COMMUNITY_WORK_PICKER_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1});
