/* Node/jsdom behavior tests for the real ESM factory; no browser or live API. */
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
const {JSDOM}=process.env.WEB_DOM_MODULE?require(process.env.WEB_DOM_MODULE):require('jsdom');
const root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/web-shell-tests'));
const tick=()=>new Promise(r=>setImmediate(r));
const auth=(name='alpha',balance=0)=>({auth_source:'site',manual_credit_only:true,token:'fixture-token-'+name,csrf_token:'fixture-csrf',user:{user_id:'SHARED_'+name,account_user_id:'SITE_'+name,username:name,nickname:name,account_type:'site',wechat_bound:false},balance,wechat_login:{enabled:false,ready:false}});
const response=(data,status=200)=>({ok:status>=200&&status<300,status,json:async()=>data});
async function fixture(options={}){
 const {createApplication}=await import(pathToFileURL(path.join(root,'backend/static/web/app.js')).href);
 const dom=new JSDOM('<!doctype html><div id="app"></div>',{url:'http://fixture.local/',pretendToBeVisual:true});dom.window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};dom.window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
 const calls=[],mounts=[],cleanups=[],locations=[],doc=dom.window.document;
 const fetch=async(url,init)=>{const request={url,init,body:init.body?JSON.parse(init.body):null};calls.push(request);if(options.fetch)return options.fetch(url,init,request);
  if(url==='/api/config')return response({prices:{light:40,fine:40},text_generation:{ready:true,price:40}});
  if(url==='/api/auth/site/session')return options.session?response(options.session):response({detail:'请先登录'},401);
  if(['/api/auth/site/login','/api/auth/site/register'].includes(url))return response(auth(request.body.username,0));
  if(url==='/api/auth/site/password')return response({ok:true,login_required:true});if(url==='/api/auth/site/logout')return response({ok:true});if(url==='/api/me')return response({balance:125,nickname:'服务器昵称'});return response({ok:true});};
 const mount=async(ctx,view,route,params)=>{mounts.push({ctx,view,route,params});view.append(doc.createElement('h1'));view.firstChild.textContent=route;return ()=>cleanups.push(route);};
 const app=createApplication({document:doc,fetch,disableHistory:true,mountCreation:options.mountCreation||mount,mountLibrary:options.mountLibrary||mount,assignLocation:url=>locations.push(url),...options.appOptions});
 return {app,dom,doc,calls,mounts,cleanups,locations,finish(){app.destroy();dom.window.close();}};
}
function click(t,selector){const b=t.doc.querySelector(selector);assert(b,'Missing '+selector);b.click();}
function fill(t,label,value){const field=t.doc.querySelector('[aria-label="'+label+'"]');assert(field,'Missing input '+label);field.value=value;}
function submit(t){const form=t.doc.querySelector('dialog form');assert(form);form.dispatchEvent(new t.dom.window.Event('submit',{bubbles:true,cancelable:true}));}
async function login(t,name='alpha',mode='login'){const pending=t.app.requireLogin();if(mode==='register')click(t,'[data-action="register-mode"]');fill(t,'用户名',name);fill(t,'密码','fixture-password');if(mode==='register')fill(t,'确认密码','fixture-password');submit(t);assert(await pending);await tick();}

async function runRaceScenario(name){
 if(name==='startup_late'){
  let releaseSession,releaseLogin;const t=await fixture({fetch:async(url,init)=>{
   if(url==='/api/config')return response({prices:{light:40,fine:40}});if(url==='/api/auth/site/session')return new Promise(r=>releaseSession=r);
   if(url==='/api/auth/site/login')return new Promise(r=>releaseLogin=r);return response({ok:true});}});
  const start=t.app.start();await tick();const pending=t.app.requireLogin();fill(t,'用户名','new_account');fill(t,'密码','fixture-password');submit(t);await tick();
  releaseSession(response(auth('old_cookie',999)));await tick();assert.equal(t.app.state.user,null);assert(t.doc.querySelector('dialog'));
  releaseLogin(response(auth('new_account',7)));assert(await pending);await start;assert.equal(t.app.state.user.username,'new_account');assert.equal(t.app.state.user.balance,7);const observed={username:t.app.state.user.username,balance:t.app.state.user.balance};t.finish();return observed;
 }
 if(name==='modal_pending_lock'){
  let release;const t=await fixture({fetch:async(url,init)=>url==='/api/auth/site/login'?new Promise(r=>release=r):url==='/api/config'?response({}):response({detail:'匿名'},401)});await t.app.start();const first=t.app.requireLogin();fill(t,'用户名','first_user');fill(t,'密码','fixture-password');submit(t);await tick();click(t,'.shell-dialog-close');click(t,'[data-action="register-mode"]');const second=t.app.requireLogin();submit(t);await tick();
  assert.equal(first,second);assert(t.doc.querySelector('dialog'));assert.equal(t.calls.filter(c=>c.url.endsWith('/login')).length,1);assert.equal(t.calls.filter(c=>c.url.endsWith('/register')).length,0);
  release(response(auth('first_user',0)));assert(await first);const observed={loginPosts:1,registerPosts:0,closeWhilePendingBlocked:true};t.finish();return observed;
 }
 if(name==='newer_summary'){
  const resolves=[];const t=await fixture({fetch:async url=>url==='/api/config'?response({}):url==='/api/auth/site/session'?response(auth('alpha',0)):url==='/api/me'?new Promise(r=>resolves.push(r)):response({ok:true})});await t.app.start();const a=t.app.invalidateAccount(),b=t.app.invalidateAccount();await tick();resolves[1](response({balance:8,nickname:'最新昵称'}));await b;resolves[0](response({balance:999,nickname:'过时昵称'}));await a;
  assert.equal(t.app.state.user.nickname,'最新昵称');assert.equal(t.app.state.user.balance,8);const observed={balance:8,nickname:'最新昵称',summaryRequests:2};t.finish();return observed;
 }
 throw Error('Unknown race scenario '+name);
}
async function run(){
 const cases=[];async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name);}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
 await test('startup_config_and_cookie_session_begin_in_parallel',async()=>{let config,session;const t=await fixture({fetch:url=>url==='/api/config'?new Promise(r=>config=r):new Promise(r=>session=r)});const start=t.app.start();assert.deepEqual(t.calls.map(c=>c.url),['/api/config','/api/auth/site/session']);session(response(auth('alpha',0)));config(response({prices:{light:40}}));await start;assert.equal(t.app.state.config.prices.light,40);assert.equal(t.app.state.user.balance,0);t.finish();});
 await test('anonymous_boot_is_public_and_never_creates_a_visitor',async()=>{const t=await fixture();await t.app.start();assert.deepEqual(t.calls.map(c=>c.url),['/api/config','/api/auth/site/session']);assert.equal(t.app.state.user,null);assert.equal(t.doc.querySelectorAll('dialog').length,0);assert.equal(t.mounts[0].route,'create');t.finish();});
 await test('cookie_session_without_token_restores_header_and_uses_same_origin_requests',async()=>{const session=auth('cookie_user',245);delete session.token;delete session.csrf_token;const t=await fixture({session});await t.app.start();assert(t.doc.body.textContent.includes('✦ 245'));await t.app.api('/api/me');const call=t.calls.at(-1);assert.equal(call.init.credentials,'same-origin');assert.equal(call.init.headers['X-Site-Request'],'1');assert(!call.init.headers.Authorization);t.finish();});
 await test('four_navigation_tabs_mount_correct_modules_and_clean_previous_view',async()=>{const t=await fixture();await t.app.start();click(t,'[data-route="templates"]');await tick();click(t,'button[data-route="community"]');await tick();assert.deepEqual(t.mounts.map(m=>m.route),['create','templates','community']);assert.deepEqual(t.cleanups,['create','templates']);assert.equal(t.doc.querySelector('[aria-current="page"]').dataset.route,'community');t.finish();});
 await test('blob_and_recipe_navigation_remain_in_memory_not_serialized',async()=>{const t=await fixture();await t.app.start();const blob=new Blob(['fixture']),recipe={input_mode:'photo',blob};await t.app.navigate('create',{initialDraft:recipe});assert.equal(t.mounts.at(-1).params.initialDraft.blob,blob);assert.equal(t.dom.window.location.hash,'');t.finish();});
 await test('registration_requires_confirmation_and_keeps_username_on_errors',async()=>{const t=await fixture();await t.app.start();const pending=t.app.requireLogin();click(t,'[data-action="register-mode"]');fill(t,'用户名','Test_User');fill(t,'密码','fixture-password');fill(t,'确认密码','mismatch');submit(t);await tick();assert(t.doc.querySelector('.shell-error').textContent.includes('不一致'));assert.equal(t.calls.length,2);assert.equal(t.doc.querySelector('[aria-label="用户名"]').value,'Test_User');fill(t,'确认密码','fixture-password');submit(t);assert(await pending);assert.equal(t.calls.at(-1).body.username,'test_user');assert.equal(t.app.state.user.balance,0);assert.equal(t.app.state.auth.manual_credit_only,true);t.finish();});
 await test('registration_modal_explains_zero_balance_and_manual_credit_only',async()=>{const t=await fixture();await t.app.start();t.app.requireLogin();assert(t.doc.querySelector('dialog').textContent.includes('初始为 0 光子'));assert(t.doc.querySelector('dialog').textContent.includes('后台手动增加'));click(t,'.shell-dialog-close');t.finish();});
 await test('login_validation_and_server_errors_preserve_editable_identity',async()=>{const t=await fixture({fetch:async url=>url==='/api/auth/site/login'?response({detail:'用户名或密码错误'},401):url==='/api/config'?response({}):response({detail:'匿名'},401)});await t.app.start();t.app.requireLogin();fill(t,'用户名','user_ok');fill(t,'密码','short');submit(t);await tick();assert(t.doc.querySelector('.shell-error').textContent.includes('10–128'));fill(t,'密码','fixture-password');submit(t);await tick();assert(t.doc.querySelector('.shell-error').textContent.includes('用户名或密码'));assert.equal(t.doc.querySelector('[aria-label="用户名"]').value,'user_ok');assert(!t.doc.querySelector('[data-action="auth-submit"]').disabled);click(t,'.shell-dialog-close');t.finish();});
 await test('auth_token_and_csrf_stay_in_memory_and_are_sent_only_to_api',async()=>{const t=await fixture();let writes=0;t.dom.window.localStorage.setItem=()=>writes++;await t.app.start();await login(t);await t.app.api('/api/me/profile',{method:'POST',data:{nickname:'test'}});const call=t.calls.at(-1);assert.equal(call.init.headers.Authorization,'Bearer fixture-token-alpha');assert.equal(call.init.headers['X-CSRF-Token'],'fixture-csrf');assert.equal(call.init.headers['X-Site-CSRF'],'fixture-csrf');assert.equal(writes,0);await assert.rejects(t.app.api('https://foreign.invalid/api/me'));t.finish();});
 await test('api_error_retains_status_detail_and_structured_response',async()=>{const t=await fixture({fetch:async()=>response({detail:'额度不足',required:40},402)});let error;try{await t.app.api('/api/rescue/by-upload',{method:'POST',data:{}});}catch(e){error=e;}assert.equal(error.status,402);assert.equal(error.detail,'额度不足');assert.equal(error.data.required,40);t.finish();});
 await test('current_creation_is_not_remounted_automatically_after_login',async()=>{const t=await fixture();await t.app.start();const mounts=t.mounts.length;await login(t);assert.equal(t.mounts.length,mounts);assert.equal(t.app.accountVersion,1);t.finish();});
 await test('logged_in_private_route_remounts_after_registration',async()=>{const t=await fixture({appOptions:{initialRoute:'my'}});await t.app.start();await login(t);await tick();assert.equal(t.mounts.at(-1).route,'my');assert.equal(t.mounts.at(-1).ctx.state.user.username,'alpha');t.finish();});
 await test('guest_first_comment_survives_real_shell_login_remount_and_needs_explicit_resend',async()=>{
  const {mountLibrary}=await import(pathToFileURL(path.join(root,'backend/static/web/library.js')).href);let posts=0,posted='';
  const t=await fixture({mountLibrary,appOptions:{initialRoute:'post',initialParams:{id:'post1'}},fetch:async(url,init,req)=>{
   if(url==='/api/config')return response({});if(url==='/api/auth/site/session')return response({detail:'匿名'},401);if(url==='/api/auth/site/login')return response(auth('alpha',0));
   if(url==='/api/community/posts/post1')return response({post:{id:'post1',title:'公开作品',authorName:'作者',date:'今天',resultUrl:'https://cos.invalid/fixture.jpg',likes:0}});
   if(req.init.method==='POST'&&url.endsWith('/comments')){posts++;posted=req.body.content;return response({ok:true});}return response({items:[],has_more:false,next_offset:0,total:0});
  }});await t.app.start();await tick();const input=t.doc.querySelector('.lib-composer textarea');input.value='第一次留言';input.dispatchEvent(new t.dom.window.Event('input',{bubbles:true}));t.doc.querySelector('.lib-composer').dispatchEvent(new t.dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();await login(t);await tick();await tick();
  assert.equal(posts,0);assert.equal(t.doc.querySelector('.lib-composer textarea').value,'第一次留言');assert(t.doc.querySelector('.site-toast').textContent.includes('再次点击'));
  t.doc.querySelector('.lib-composer').dispatchEvent(new t.dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();await tick();assert.equal(posts,1);assert.equal(posted,'第一次留言');t.finish();
 });
 await test('inflight_comment_locks_textarea_and_snapshot_guard_preserves_unsent_text',async()=>{
  const {mountLibrary}=await import(pathToFileURL(path.join(root,'backend/static/web/library.js')).href);let release,posted;
  const t=await fixture({mountLibrary,appOptions:{initialRoute:'post',initialParams:{id:'post1'}},fetch:async(url,init,req)=>{
   if(url==='/api/config')return response({});if(url==='/api/auth/site/session')return response(auth('alpha',0));if(url==='/api/community/posts/post1')return response({post:{id:'post1',title:'公开作品',authorName:'作者',date:'今天',resultUrl:'https://cos.invalid/fixture.jpg',likes:0}});
   if(req.init.method==='POST'&&url.endsWith('/comments')){posted=req.body.content;return new Promise(r=>release=r);}return response({items:[],has_more:false,next_offset:0,total:0});
  }});await t.app.start();await tick();const input=t.doc.querySelector('.lib-composer textarea');input.value='first';t.doc.querySelector('.lib-composer').dispatchEvent(new t.dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();assert(input.disabled);
  input.value='second';input.dispatchEvent(new t.dom.window.Event('input',{bubbles:true}));release(response({ok:true}));await tick();await tick();assert.equal(posted,'first');assert.equal(input.value,'second');assert(!input.disabled);t.finish();
 });
 await test('guest_public_like_login_is_explicitly_retryable_not_silently_consumed',async()=>{
  const {mountLibrary}=await import(pathToFileURL(path.join(root,'backend/static/web/library.js')).href);let likes=0;
  const t=await fixture({mountLibrary,appOptions:{initialRoute:'community'},fetch:async(url,init,req)=>{
   if(url==='/api/config')return response({});if(url==='/api/auth/site/session')return response({detail:'匿名'},401);if(url==='/api/auth/site/login')return response(auth('alpha',0));
   if(url.includes('/like')){likes++;return response({id:'post1',liked:true,likes:1});}return response({enabled:true,items:[{id:'post1',title:'公开作品',authorName:'作者',resultUrl:'https://cos.invalid/image.jpg',likes:0,liked:false}],has_more:false,next_offset:1});
  }});await t.app.start();await tick();click(t,'[data-action="like-post"]');await tick();await login(t);await tick();await tick();assert.equal(likes,0);assert(t.doc.querySelector('.site-toast').textContent.includes('再次点击'));click(t,'[data-action="like-post"]');await tick();assert.equal(likes,1);t.finish();
 });
 await test('logout_revokes_session_stops_old_view_and_keeps_cloud_data',async()=>{const t=await fixture({session:auth('alpha',7)});await t.app.start();await t.app.navigate('works');await t.app.logout();assert.equal(t.app.state.user,null);assert.equal(t.app.state.auth,null);assert.equal(t.app.current.route,'create');assert(t.cleanups.includes('works'));assert(t.calls.some(c=>c.url==='/api/auth/site/logout'&&c.init.method==='POST'));assert(!t.calls.some(c=>c.init.method==='DELETE'));t.finish();});
 await test('password_change_requires_relogin_and_clears_existing_session',async()=>{const t=await fixture({session:auth('alpha',7)});await t.app.start();const pending=t.app.changePassword();fill(t,'当前密码','old-password');fill(t,'新密码','new-password1');fill(t,'再次确认新密码','new-password1');submit(t);assert(await pending);assert.equal(t.app.state.user,null);assert(t.calls.some(c=>c.url==='/api/auth/site/password'&&c.body.current_password==='old-password'));t.finish();});
 await test('unconfigured_wechat_link_is_explanatory_and_does_not_start_oauth',async()=>{const t=await fixture({session:auth()});await t.app.start();await t.app.startWechatLink();assert(t.doc.querySelector('.site-toast').textContent.includes('尚未配置'));assert(!t.calls.some(c=>c.url.endsWith('/wechat/start')));assert.equal(t.locations.length,0);t.finish();});
 await test('configured_wechat_link_only_accepts_official_https_oauth_target',async()=>{const session=auth();session.wechat_login.ready=true;const t=await fixture({fetch:async url=>url==='/api/config'?response({}):url==='/api/auth/site/session'?response(session):response({url:'https://open.weixin.qq.com/connect/qrconnect?fixture=1'})});await t.app.start();await t.app.startWechatLink();assert.equal(t.locations.length,1);assert(t.calls.at(-1).body.mode==='bind');t.finish();});
 await test('forged_wechat_redirect_target_is_rejected_before_navigation',async()=>{const session=auth();session.wechat_login.ready=true;const t=await fixture({fetch:async url=>url==='/api/config'?response({}):url==='/api/auth/site/session'?response(session):response({url:'https://open.weixin.qq.com.evil.invalid/'})});await t.app.start();await assert.rejects(t.app.startWechatLink());assert.equal(t.locations.length,0);t.finish();});
 await test('old_balance_response_cannot_replace_newer_same_view_summary',()=>runRaceScenario('newer_summary'));
 await test('initial_cookie_session_cannot_replace_explicit_new_login',()=>runRaceScenario('startup_late'));
 await test('pending_login_locks_close_mode_switch_and_second_identity_request',()=>runRaceScenario('modal_pending_lock'));
 await test('balance_response_from_old_route_generation_is_discarded',async()=>{let release;const t=await fixture({fetch:async url=>url==='/api/config'?response({}):url==='/api/auth/site/session'?response(auth('alpha',5)):new Promise(r=>release=r)});await t.app.start();const pending=t.app.api('/api/me');await t.app.navigate('community');release(response({balance:999}));await pending;assert.equal(t.app.state.user.balance,5);t.finish();});
 await test('destroy_cancels_auth_wait_and_removes_all_owned_ui',async()=>{const t=await fixture();await t.app.start();const pending=t.app.requireLogin();t.app.destroy();assert.equal(await pending,false);assert.equal(t.doc.querySelectorAll('dialog').length,0);assert.equal(t.doc.querySelectorAll('.site-shell').length,0);t.dom.window.close();});
 await test('privacy_and_retention_use_real_shared_storage_and_30_day_explanations',async()=>{const t=await fixture();await t.app.start();await t.app.navigate('privacy');assert(t.doc.body.textContent.includes('默认私密'));assert(t.doc.body.textContent.includes('浏览器本地'));await t.app.navigate('retention');assert(t.doc.body.textContent.includes('保留 30 天'));assert(t.doc.body.textContent.includes('社区副本独立'));t.finish();});
 await test('static_index_has_seo_favicon_noscript_and_external_esm_modules',()=>{const index=fs.readFileSync(path.join(root,'backend/index.html'),'utf8'),dom=new JSDOM(index),doc=dom.window.document;assert(doc.querySelector('meta[name="description"]'));assert(doc.querySelector('link[rel="icon"]'));assert(doc.querySelector('noscript'));assert.equal(doc.querySelector('script[type="module"]').getAttribute('src'),'/web-assets/boot.js');assert.equal(doc.querySelectorAll('script:not([src])').length,0);assert.deepEqual(Array.from(doc.querySelectorAll('link[rel="stylesheet"]'),link=>link.getAttribute('href')),['/web-assets/shell.css','/web-assets/creation.css','/web-assets/library.css']);dom.window.close();});
 const failed=cases.filter(c=>!c.passed).length;fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'web_shell_results.json'),JSON.stringify({cases,total:cases.length,failed},null,2),'utf8');console.log(`WEB_SHELL_SUMMARY total=${cases.length} passed=${cases.length-failed} failed=${failed}`);return failed;
}
module.exports={fixture,runRaceScenario,auth,response};if(require.main===module)run().then(failed=>{process.exitCode=failed?1:0;}).catch(e=>{console.error(e.stack);process.exitCode=1;});
