/* Actual mini-program handlers with explicit wx action-sheet choices, no album/network I/O. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/mini-work-actions'));
const rows=[],tick=async()=>{for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));};
async function test(name,fn){try{await fn();rows.push({case:name,passed:true});console.log('PASS '+name);}catch(e){rows.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
function fixture(works,options={}){
 const events={sheets:[],previews:[],routes:[],albums:[],modals:[],toasts:[],downloads:[],deletes:[],settings:0,requests:[],recreates:[]};let page;
 const app={globalData:{historyList:works,mediaCache:{}},persist(){}};
 const api={isJobCosUrl:url=>/^https:\/\/cos\.invalid\//.test(url||''),downloadJobMedia:async(id,kind,url)=>{events.downloads.push({id,kind,url});return 'wxfile://tmp/full.jpg';},request:async url=>{events.requests.push(url);return options.latest||works[0];},deleteJob:async id=>events.deletes.push(id),absolute:url=>url,...options.api};
 const wx={showActionSheet:value=>events.sheets.push(value),previewImage:value=>events.previews.push(value),navigateTo:value=>events.routes.push(value.url),showModal:value=>events.modals.push(value),showToast:value=>events.toasts.push(value),showLoading(){},hideLoading(){},saveImageToPhotosAlbum:value=>{events.albums.push(value.filePath);options.deny?value.fail({errMsg:'saveImageToPhotosAlbum:fail auth deny'}):value.success();},openSetting:()=>events.settings++,getImageInfo:value=>value.success({path:'wxfile://tmp/legacy.jpg'})};
 vm.runInNewContext(fs.readFileSync(path.join(root,'miniprogram/pages/works/works.js'),'utf8'),{Page:x=>page=x,getApp:()=>app,require:name=>name.includes('creation-draft')?{recreateFromJob:async id=>events.recreates.push(id)}:api,wx,console,setTimeout,clearTimeout,Date});
 page.data=JSON.parse(JSON.stringify(page.data));page.data.works=works;page._visible=true;page.setData=data=>Object.assign(page.data,data);
 return {page,events,wx,api,app,event:index=>({currentTarget:{dataset:{index}}}),choose:async(label,sheet=events.sheets.at(-1))=>{const i=sheet.itemList.indexOf(label);assert(i>=0,'Missing action '+label);sheet.success({tapIndex:i});await tick();}};
}
const complete=()=>({jobId:'owned_job',status:'succeeded',result:'https://cos.invalid/full.jpg',original:'https://cos.invalid/original.jpg'});
(async()=>{
 await test('work_image_and_dots_both_open_menu_without_preview_download_or_post',async()=>{const f=fixture([complete()]);f.page.onTapWork(f.event(0));assert.equal(f.events.sheets.length,1);assert.equal(f.events.downloads.length,0);assert.equal(f.events.previews.length,0);assert.equal(f.events.requests.length,0);f.page.onMoreWork(f.event(0));assert.deepEqual(f.events.sheets[0].itemList,f.events.sheets[1].itemList);assert(!f.events.sheets[0].itemList.includes('投稿到社区'));});
 await test('view_only_runs_after_explicit_menu_choice_and_fetches_owned_hd_media',async()=>{const f=fixture([complete()]);f.page.onMoreWork(f.event(0));await f.choose('全屏高清查看');assert.equal(f.events.downloads.length,1);assert.equal(f.events.downloads[0].kind,'result');assert.equal(f.events.previews[0].current,'wxfile://tmp/full.jpg');assert.equal(f.events.albums.length,0);assert.equal(f.events.deletes.length,0);});
 await test('compare_choice_opens_compare_with_real_original_result_and_job',async()=>{const f=fixture([complete()]);f.page.onMoreWork(f.event(0));await f.choose('对比原图模式');assert(f.events.routes[0].startsWith('/pages/compare/compare?'));assert(f.events.routes[0].includes('job=owned_job'));assert(f.events.routes[0].includes(encodeURIComponent('https://cos.invalid/original.jpg')));assert.equal(f.events.albums.length,0);});
 await test('recreate_choice_is_not_misindexed_to_post_delete_or_save',async()=>{const f=fixture([complete()]);f.page.onMoreWork(f.event(0));await f.choose('沿用参数再创作');assert.deepEqual(f.events.recreates,['owned_job']);assert.equal(f.events.deletes.length,0);assert.equal(f.events.albums.length,0);assert.equal(f.events.routes.length,0);});
 await test('save_menu_reuses_existing_save_handler_helper_and_does_not_delete',async()=>{const f=fixture([complete()]);f.page.onMoreWork(f.event(0));await f.choose('保存到相册');assert.deepEqual(f.events.albums,['wxfile://tmp/full.jpg']);assert.equal(f.events.deletes.length,0);assert.equal(f.page.data.savingJobId,'');await f.page.onSaveWork(f.event(0));assert.equal(f.events.albums.length,2);});
 await test('delete_choice_still_requires_confirmation_and_keeps_selected_identity',async()=>{const f=fixture([complete()]);f.page.onMoreWork(f.event(0));const selected=f.events.sheets[0];f.page.data.works=[{...complete(),jobId:'other_job'}];await f.choose('删除此件作品',selected);assert.equal(f.events.deletes.length,0);const modal=f.events.modals.find(m=>m.title==='删除作品');assert(modal);await modal.success({confirm:true});await tick();assert.deepEqual(f.events.deletes,['owned_job']);assert.equal(f.events.albums.length,0);});
 await test('pending_and_failed_never_offer_view_compare_or_save_and_direct_helpers_reject',async()=>{for(const status of ['processing','failed']){const f=fixture([{...complete(),status,error:'测试失败'}]);f.page.onMoreWork(f.event(0));const labels=f.events.sheets[0].itemList;assert(!labels.some(x=>/高清|对比|相册/.test(x)));f.page.openWorkPreview(f.page.data.works[0]);await f.page.saveWork(f.page.data.works[0]);assert.equal(f.events.downloads.length,0);assert.equal(f.events.previews.length,0);assert.equal(f.events.albums.length,0);}});
 await test('checking_progress_never_auto_opens_even_when_task_just_completed',async()=>{const f=fixture([{jobId:'owned_job',status:'processing'}]);f.page.refreshWork=async()=>complete();f.page.onMoreWork(f.event(0));await f.choose('查看最新进度');assert.equal(f.events.previews.length,0);assert.equal(f.events.albums.length,0);assert(f.events.toasts.some(t=>t.title.includes('从更多操作中查看')));});
 await test('same_origin_legacy_bytes_are_not_used_for_preview_or_album_save',async()=>{const f=fixture([{status:'succeeded',result:'https://api.invalid/api/images/old.jpg'}]);f.page.onMoreWork(f.event(0));await f.choose('全屏高清查看');f.page.onMoreWork(f.event(0));await f.choose('保存到相册');assert.equal(f.events.previews.length,0);assert.equal(f.events.albums.length,0);assert.equal(f.events.downloads.length,0);assert(f.events.modals.length>=2);});
 await test('album_denial_asks_user_before_settings_and_never_retries_automatically',async()=>{const f=fixture([complete()],{deny:true});f.page.onMoreWork(f.event(0));await f.choose('保存到相册');assert.equal(f.events.settings,0);assert.equal(f.events.albums.length,1);const modal=f.events.modals.find(m=>m.confirmText==='去设置');assert(modal);modal.success({confirm:false});assert.equal(f.events.settings,0);modal.success({confirm:true});assert.equal(f.events.settings,1);assert.equal(f.events.albums.length,1);});
 await test('unknown_action_index_is_ignored_instead_of_triggering_delete',()=>{const f=fixture([complete()]);f.page.onMoreWork(f.event(0));f.events.sheets[0].success({tapIndex:99});assert.equal(f.events.modals.length,0);assert.equal(f.events.deletes.length,0);});
 await test('compare_has_only_bottom_save_and_keeps_original_hold_slider_gestures',()=>{const xml=fs.readFileSync(path.join(root,'miniprogram/pages/compare/compare.wxml'),'utf8');assert(!xml.includes('quick-export'));assert.equal((xml.match(/bindtap="onDownload"/g)||[]).length,1);assert(xml.includes('class="btn-ink dock-btn-save"'));assert(xml.includes('bindtouchmove="onTouchMove"'));assert(xml.includes('catchtouchstart="onPressOriginalStart"'));assert(xml.includes('style="width: {{ stageW }}px;"'));assert(xml.includes('mode="aspectFit"'));});
 await test('work_cards_have_no_save_or_submit_entry_but_community_keeps_its_own_post_flow',()=>{const xml=fs.readFileSync(path.join(root,'miniprogram/pages/works/works.wxml'),'utf8');assert(!xml.includes('work-save'));assert(!xml.includes('work-submit'));assert(!xml.includes('onSubmitWork'));const card=xml.match(/<view\s+wx:for="\{\{ filteredWorks \}\}"[\s\S]*?\n\s*>/);assert(card);assert(card[0].includes('bindtap="onMoreWork"'));assert(card[0].includes('data-index="{{ item.sourceIndex }}"'));assert(xml.includes('<view class="work-photo-box">'));assert(xml.includes('catchtap="onMoreWork"'));assert(!xml.includes('bindtap="onTapWork"'));const community=fs.readFileSync(path.join(root,'miniprogram/pages/community/community.wxml'),'utf8')+fs.readFileSync(path.join(root,'miniprogram/pages/community/community.js'),'utf8');assert(community.includes('投稿'));assert(community.includes('community-submit'));});
 fs.mkdirSync(out,{recursive:true});const passed=rows.filter(r=>r.passed).length;fs.writeFileSync(path.join(out,'mini_work_actions_results.json'),JSON.stringify({summary:{total:rows.length,passed,failed:rows.length-passed},cases:rows},null,2),'utf8');console.log(`MINI_WORK_ACTIONS_SUMMARY total=${rows.length} passed=${passed} failed=${rows.length-passed}`);process.exitCode=passed===rows.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1;});
