/* Real catalog DOM and accessible interactions. Browser geometry lives in visual QA. */
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom'),root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/web-catalog-layout')),cases=[];
const css=['shell','creation','library'].map(n=>fs.readFileSync(path.join(root,'backend/static/web',n+'.css'),'utf8')).join('\n');
const tick=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name);}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name,e);}}
(async()=>{
 const {mountCreation}=await import(pathToFileURL(path.join(root,'backend/static/web/creation.js')).href),{createApplication}=await import(pathToFileURL(path.join(root,'backend/static/web/app.js')).href);
 async function fixture(){const dom=new JSDOM('<style>'+css+'</style><main></main>',{url:'https://fixture.invalid',pretendToBeVisual:true}),doc=dom.window.document,calls=[],nav=[];
  const templates=[{id:'a',name:'水彩技术爆炸图',subtitle:'唯一的很长原始简介仍留在详情与搜索',author_name:'样例作者',source:'user',group_id:'art',usage_count:3,published_at:1,thumbnail:'https://cos.invalid/a-small',covers:['https://cos.invalid/a-hd'],guide:{advice:'选择清晰照片'}},
   {id:'b',name:'短名',subtitle:'短简介',group_id:'art',usage_count:5,published_at:2,thumbnail:'https://cos.invalid/b-small',covers:['https://cos.invalid/b-hd']},
   {id:'outside',name:'超长的风格名称应当完整保存而非截断数据',group_id:'travel',usage_count:9,published_at:3,thumbnail:'https://cos.invalid/out-small',covers:['https://cos.invalid/out-hd']}];
  let preferences={template_favorites:['a','outside'],recent_templates:['outside','b']};
  const ctx={accountVersion:1,document:doc,state:{user:{user_id:'owner'},config:{prices:{light:40,fine:80},free_mode:false}},requireLogin:async()=>true,toast(){},confirm:async()=>false,navigate:(r,p)=>nav.push({r,p}),element:(tag,cls,text)=>{const n=doc.createElement(tag);n.className=cls||'';if(text!=null)n.textContent=text;return n;},api:async(url,options)=>{calls.push({url,options});if(url==='/api/templates')return{groups:[{id:'art',name:'艺术'},{id:'travel',name:'旅行'}],items:templates};if(url==='/api/me/preferences'&&options?.method==='PUT'){const id=options.data.template_id;preferences={...preferences,template_favorites:options.data.favorite?[...preferences.template_favorites,id]:preferences.template_favorites.filter(x=>x!==id)};}return preferences;}};
  dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new dom.window.Event('close'));};
  const stop=await mountCreation(ctx,doc.querySelector('main'),'templates');await tick();return{dom,doc,calls,nav,stop,templates,close(){stop();dom.window.close();}};
 }
 const names=f=>[...f.doc.querySelectorAll('.creation-template-name')].map(n=>n.textContent),change=(f,label,value)=>{const select=f.doc.querySelector('[aria-label="'+label+'"]');select.value=value;select.dispatchEvent(new f.dom.window.Event('change'));},scope=async(f,text)=>{[...f.doc.querySelectorAll('.creation-catalog-scope button')].find(b=>b.textContent===text).click();await tick();};
 await test('catalog_cards_have_single_line_full_name_no_variable_description_and_uncropped_thumb',async()=>{const f=await fixture();try{const card=f.doc.querySelector('[data-id="a"]')||[...f.doc.querySelectorAll('.creation-template-card')].find(c=>c.querySelector('h3').textContent==='水彩技术爆炸图');assert(!card.textContent.includes('唯一的很长'));assert(!card.textContent.includes('样例作者'));const title=card.querySelector('.creation-template-name'),s=f.dom.window.getComputedStyle(title);assert.equal(title.title,title.textContent);assert.equal(s.whiteSpace,'nowrap');assert.equal(s.textOverflow,'ellipsis');assert.equal(card.querySelector('img').src,'https://cos.invalid/a-small');assert.equal(f.dom.window.getComputedStyle(card.querySelector('img')).objectFit,'contain');}finally{f.close();}});
 await test('favorite_is_independent_cover_overlay_not_nested_button_and_does_not_steal_title_width',async()=>{const f=await fixture();try{for(const card of f.doc.querySelectorAll('.creation-template-card')){const star=card.querySelector('.creation-favorite');assert(!star.closest('.creation-template-preview'));assert(!card.querySelector('button button'));assert.equal(star.parentElement.className,'creation-template-media');const s=f.dom.window.getComputedStyle(star);assert.equal(s.position,'absolute');assert.equal(s.right,'8px');assert.equal(s.bottom,'8px');assert.equal(card.querySelector('.creation-template-title-row').children.length,1);assert(star.hasAttribute('aria-pressed'));}}finally{f.close();}});
 await test('filters_are_one_category_sort_row_and_contribution_actions_live_in_my_not_catalog',async()=>{const f=await fixture();try{assert.equal(f.doc.querySelectorAll('.creation-catalog-filters').length,1);assert.equal(f.doc.querySelectorAll('.creation-catalog-filters select').length,2);assert.equal(f.doc.querySelectorAll('.creation-catalog-scope button').length,3);assert(!f.doc.querySelector('.creation-heading').textContent.includes('分享模板'));assert.equal(f.doc.querySelector('[aria-label="模板排序"]').value,'hot');change(f,'模板分类','art');assert(f.doc.querySelector('[aria-label="模板排序"]').disabled);assert(f.doc.querySelector('[aria-label="模板排序"]').selectedOptions[0].textContent==='分类顺序');}finally{f.close();}});
 await test('favorites_and_recent_hide_filters_ignore_last_group_and_keep_their_visible_sequence',async()=>{const f=await fixture();try{change(f,'模板排序','latest');change(f,'模板分类','art');await scope(f,'我的收藏');assert.equal(f.doc.querySelector('.creation-catalog-filters'),null);assert.deepEqual(names(f),['水彩技术爆炸图','超长的风格名称应当完整保存而非截断数据']);await scope(f,'最近使用');assert.deepEqual(names(f),['超长的风格名称应当完整保存而非截断数据','短名']);await scope(f,'全部模板');assert.equal(f.doc.querySelector('[aria-label="模板分类"]').value,'art');assert.equal(f.doc.querySelectorAll('.creation-template-card').length,2);}finally{f.close();}});
 await test('hidden_subtitle_still_matches_search_without_corrupting_full_metadata',async()=>{const f=await fixture();try{const search=f.doc.querySelector('[aria-label="搜索风格"]');search.value='唯一的很长';search.dispatchEvent(new f.dom.window.Event('input'));assert.deepEqual(names(f),['水彩技术爆炸图']);assert.equal(f.templates[0].subtitle,'唯一的很长原始简介仍留在详情与搜索');}finally{f.close();}});
 await test('details_open_at_top_with_focusable_heading_visible_close_full_cover_and_original_advice',async()=>{const f=await fixture();try{const card=[...f.doc.querySelectorAll('.creation-template-card')].find(c=>c.querySelector('h3').textContent==='水彩技术爆炸图');card.querySelector('.creation-template-preview').click();const dialog=f.doc.querySelector('dialog'),heading=dialog.querySelector('.creation-detail-heading h2');assert(dialog.open);assert.equal(dialog.scrollTop,0);assert.equal(f.doc.activeElement,heading);assert.equal(heading.tabIndex,-1);assert(dialog.querySelector('.creation-dialog-close'));assert.equal(dialog.querySelector('img').src,'https://cos.invalid/a-hd');assert(dialog.textContent.includes('唯一的很长'));assert(dialog.textContent.includes('分享者：样例作者'));[...dialog.querySelectorAll('button')].find(b=>b.textContent==='使用这个风格').click();assert.equal(f.nav[0].r,'create');assert.equal(f.nav[0].p.templateId,'a');assert(!f.calls.some(x=>x.options?.method==='POST'));}finally{f.close();}});
 await test('favorite_click_only_mutates_existing_preference_contract_not_detail_or_generation',async()=>{const f=await fixture();try{const star=[...f.doc.querySelectorAll('.creation-template-card')].find(c=>c.querySelector('h3').textContent==='短名').querySelector('.creation-favorite');star.click();await tick();assert.equal(f.doc.querySelector('dialog'),null);const writes=f.calls.filter(x=>x.options?.method);assert.equal(writes.length,1);assert.equal(writes[0].url,'/api/me/preferences');assert.equal(writes[0].options.method,'PUT');assert.deepEqual(writes[0].options.data,{template_id:'b',favorite:true});}finally{f.close();}});
 await test('explicit_checkbox_class_does_not_depend_on_has_selector_and_all_surfaces_are_square',()=>{assert(!css.includes(':has('));for(const name of ['shell','creation','library']){const t=fs.readFileSync(path.join(root,'backend/static/web',name+'.css'),'utf8');assert(!/border-radius:\s*(?:[1-9]|\.\d)/.test(t),name);}assert(css.includes('.template-share-consent>span'));assert(css.includes('.creation-checkbox-field'));});
 await test('shell_uses_local_inline_svg_icons_and_ellipsis_retains_account_name',async()=>{const dom=new JSDOM('<div id="app"></div>',{url:'https://fixture.invalid',pretendToBeVisual:true}),name='特别长的用户昵称完整保留';const app=createApplication({document:dom.window.document,disableHistory:true,initialRoute:'templates',mountCreation:async()=>()=>{},fetch:async url=>({ok:true,status:200,json:async()=>url.includes('/session')?{auth_source:'site',user:{user_id:'owner',nickname:name},balance:0}:{prices:{light:40,fine:80}}})});try{await app.start();const doc=dom.window.document;assert.equal(doc.querySelectorAll('.site-tabs svg').length,4);assert.equal(doc.querySelectorAll('.site-tabs img').length,0);assert.equal(doc.querySelector('.site-account-label').textContent,name);assert.equal(doc.querySelector('.site-account').title,name);}finally{app.destroy();dom.window.close();}});
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'web_catalog_layout_results.json'),JSON.stringify({cases},null,2),'utf8');const passed=cases.filter(x=>x.passed).length;console.log(`WEB_CATALOG_LAYOUT_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1});
