/* Bounded read-only ledger UI: no payment/earn writes are replayed here. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/mini-credit-history')),cases=[];
function page(api){let p;const app={globalData:{lightPoints:40},setBalance(){}};vm.runInNewContext(fs.readFileSync(path.join(root,'miniprogram/pages/credits/credits.js'),'utf8'),{Page:v=>p=v,getApp:()=>app,require:()=>api,wx:{navigateTo(){},showToast(){}},console,setTimeout,clearTimeout,Date});p.data=JSON.parse(JSON.stringify(p.data));p.setData=x=>Object.assign(p.data,x);return p;}
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name)}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name,e)}}
(async()=>{
 await test('first_page_requests_twenty_and_only_five_visible_until_expanded',async()=>{let request;const p=page({request:async url=>{request=url;return {items:Array.from({length:20},(_,i)=>({id:'a'+i,amount:i%2?-40:40,title:'记录',created_at:1})),total:65,next_offset:20,has_more:true}}});await p.loadRecords();assert(request.includes('limit=20&offset=0'));assert.equal(p.data.records.length,20);assert.equal(p.data.visibleRecords.length,5);assert.equal(p.data.recordsPage,1);p.onToggleRecords();assert.equal(p.data.visibleRecords.length,20);p.onToggleRecords();assert.equal(p.data.visibleRecords.length,5);assert.equal(p.data.recordTotal,65)});
 await test('next_and_previous_replace_page_never_append_all_history',async()=>{const seen=[],p=page({request:async url=>{seen.push(url);const offset=Number(url.split('offset=')[1]);return {items:Array.from({length:20},(_,i)=>({id:String(offset+i),amount:40,title:'记录',created_at:1})),total:80,next_offset:offset+20,has_more:offset<60}}});await p.loadRecords();p.onToggleRecords();await p.onMoreRecords();assert.equal(p.data.records.length,20);assert.equal(p.data.records[0].id,'20');assert.equal(p.data.recordsPage,2);assert.equal(p.data.recordsExpanded,false);await p.onMoreRecords();assert.equal(p.data.records[0].id,'40');await p.onPrevRecords();assert.equal(p.data.records[0].id,'20');assert.equal(p.data.recordsPage,2);assert(seen.every(x=>x.startsWith('/api/me/credits?')))});
 await test('failed_next_page_keeps_current_rows_and_retry_uses_current_page',async()=>{let bad=false;const p=page({request:async url=>{if(bad)throw Error('offline');return {items:[{id:'only',amount:0,title:'待冲正',created_at:1}],total:30,next_offset:20,has_more:true}}});await p.loadRecords();bad=true;await p.onMoreRecords();assert.equal(p.data.records[0].id,'only');assert.equal(p.data.recordsPage,1);assert.equal(p.data.recordsError,'offline');bad=false;await p.onRetryRecords();assert.equal(p.data.recordsPage,1);assert.equal(p.data.visibleRecords[0].amountText,'0')});
 await test('malformed_nonprogressing_pagination_is_visible_error_not_repeat_loop',async()=>{const p=page({request:async()=>({items:[{id:'one',amount:1,created_at:1}],total:10,next_offset:0,has_more:true})});await p.loadRecords();assert(p.data.recordsError.includes('分页数据异常'));assert.equal(p.data.records.length,0)});
 await test('late_old_refresh_cannot_replace_newer_page_or_apply_after_unload',async()=>{let resolve;const p=page({request:()=>new Promise(r=>resolve=r)});const first=p.loadRecords();const firstResolve=resolve;const second=p.loadRecords();resolve({items:[{id:'new',amount:2,created_at:1}],total:1,next_offset:1,has_more:false});await second;firstResolve({items:[{id:'old',amount:1,created_at:1}],total:1,next_offset:1,has_more:false});await first;assert.equal(p.data.records[0].id,'new');const pending=p.loadRecords();p._unloaded=true;resolve({items:[],total:0,next_offset:0,has_more:false});await pending;assert.equal(p.data.records[0].id,'new')});
 await test('ledger_xml_uses_visible_rows_and_paging_buttons_not_unbounded_more',()=>{const xml=fs.readFileSync(path.join(root,'miniprogram/pages/credits/credits.wxml'),'utf8');assert(xml.includes('wx:for="{{ visibleRecords }}"'));assert(xml.includes('onToggleRecords'));assert(xml.includes('onPrevRecords'));assert(xml.includes('下一页'));assert(!xml.includes('更多明细'))});
 await test('checkin_claim_and_invite_buttons_center_and_invite_is_small_right_aligned',()=>{const css=fs.readFileSync(path.join(root,'miniprogram/pages/credits/credits.wxss'),'utf8'),invite=fs.readFileSync(path.join(root,'miniprogram/pages/invite/invite.wxss'),'utf8');assert(/checkin-claim\s*\{[^}]*display:flex[^}]*align-items:center[^}]*justify-content:center/.test(css));assert(/invite-main-btn\s*\{[^}]*width:auto[^}]*max-width:300rpx[^}]*margin:0 0 0 auto/.test(invite));assert(/banner-btn\s*\{[^}]*max-width:156rpx/.test(css))});
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'mini_credit_history_results.json'),JSON.stringify({cases},null,2),'utf8');const passed=cases.filter(x=>x.passed).length;console.log(`MINI_CREDIT_HISTORY_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1});
