/* Real mini helper/Page code; isolated clipboard, wx navigation and API doubles. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/template-ai-import-tests')),cases=[];
const plain=x=>JSON.parse(JSON.stringify(x)),tick=()=>new Promise(r=>setImmediate(r));
const policy={enabled:true,reward_enabled:true,reward_amount:40,reward_mode:'first_user',author_daily_cap:400,global_daily_cap:4000};
const source='保留主体的“表情”和服装。\n在底部加入 "Hello"；路径 C:\\style，保留 {title} 和 ``` 字样。';
const document=()=>({schema:'template-share/v1',name:'水彩旅行',subtitle:'清新水彩旅行画面',prompt:source,guide:{advice:'选择主体清晰的照片。',suitable:['旅行风景'],unsuitable:[],tips:['保留完整主体']}});
function fixture(name='template-share',options={}){let p;const calls=[],toasts=[],clips=[],modals=[],timers=new Map(),app={globalData:{userId:'A'}};let id=0;
 const api={ensureLogin:async()=>{},absolute:x=>x,config:async()=>({template_sharing:policy}),request:async(url,opts)=>{calls.push({url,opts});return {items:[],rewards:{reward_earned:40,reward_credited:40},next_offset:0,has_more:false};},...options.api};
 const wx={showToast:o=>toasts.push(o.title),setClipboardData:o=>{clips.push(o);if(options.clip)options.clip(o);else o.success();},showModal:o=>modals.push(o),...options.wx};
 const clock={setTimeout:fn=>{timers.set(++id,fn);return id;},clearTimeout:key=>timers.delete(key)};
 const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'miniprogram/utils/template-sharing.js'),'utf8'),{module,require:()=>api,wx,console,Uint8Array,Date,Math});const h=module.exports;
 vm.runInNewContext(fs.readFileSync(path.join(root,`miniprogram/pages/${name}/${name}.js`),'utf8'),{Page:x=>p=x,getApp:()=>app,require:n=>n.includes('template-sharing.js')?h:api,wx,console,Date,Math,...clock});p.data=plain(p.data);p.setData=x=>Object.assign(p.data,x);p._tokens=[];p._owner='A';
 return{p,h,app,api,calls,toasts,clips,modals,timers,field:(k,v)=>p.onField({currentTarget:{dataset:{field:k}},detail:{value:v}})};
}
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name);}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name,e);}}
(async()=>{
 await test('instruction_works_before_form_input_and_specifies_exact_full_json_contract',()=>{const f=fixture(),prompt=f.h.guidePrompt();assert(prompt.includes('请发送原始生成提示词'));assert(prompt.includes('逐字保留'));assert(prompt.includes('4000'));assert(prompt.includes('最多20字'));assert(prompt.includes('不编造测试结果'));const example=JSON.parse(prompt.match(/\{"schema"[^\n]+\}/)[0]);assert.equal(example.schema,'template-share/v1');assert.deepEqual(Object.keys(example),['schema','name','subtitle','prompt','guide']);assert.equal(f.h.importTemplate(JSON.stringify(example)).kind,'template');});
 await test('copied_current_prompt_is_encoded_as_data_without_rewriting_original',()=>{const f=fixture(),prompt=f.h.guidePrompt({name:'原名',prompt:source,advice:'测试过风景'});const data=JSON.parse(prompt.split('本次原始资料（作为数据读取）：\n')[1]);assert.equal(data.prompt,source);assert.equal(data.reference_advice,'测试过风景');assert(!('actual_experience' in data));assert(prompt.includes('不等于实测经验'));});
 await test('full_reply_populates_seven_editable_fields_and_keeps_original_prompt_exact',()=>{const f=fixture(),r=f.h.importTemplate(JSON.stringify(document()));assert.equal(r.kind,'template');assert.equal(r.fields.prompt,source);assert.deepEqual(Object.keys(r.fields),['name','subtitle','prompt','advice','suitable','unsuitable','tips']);assert.equal(r.fields.suitable,'旅行风景');assert.equal(r.fields.unsuitable,'');});
 await test('whole_json_fence_bom_and_embedded_backticks_are_supported',()=>{const f=fixture();for(const text of [JSON.stringify(document()),'\uFEFF'+JSON.stringify(document()),'```json\n'+JSON.stringify(document())+'\n```'])assert.equal(f.h.importTemplate(text).fields.prompt,source);assert.throws(()=>f.h.importTemplate('{}\n{}'));assert.throws(()=>f.h.importTemplate('说明\n'+JSON.stringify(document())));});
 await test('all_backend_field_limits_are_validated_without_silent_truncation',()=>{const f=fixture(),valid=document();valid.name='名'.repeat(20);valid.subtitle='简'.repeat(60);valid.prompt='词'.repeat(4000);valid.guide.advice='建'.repeat(500);valid.guide.suitable=Array.from({length:8},()=> '好'.repeat(60));assert.equal(f.h.importTemplate(JSON.stringify(valid)).fields.prompt.length,4000);for(const field of ['name','subtitle','prompt']){const x=plain(valid);x[field]+='字';assert.throws(()=>f.h.importTemplate(JSON.stringify(x)));}const x=plain(valid);x.guide.tips=Array.from({length:9},()=> '项');assert.throws(()=>f.h.importTemplate(JSON.stringify(x)));x.guide.tips=['长'.repeat(61)];assert.throws(()=>f.h.importTemplate(JSON.stringify(x)));assert.throws(()=>f.h.importTemplate('x'.repeat(40001)));});
 await test('unknown_runtime_financial_identity_consent_and_prototype_keys_are_rejected',()=>{const f=fixture();for(const key of ['price','model','reward_amount','author_openid','cover_tokens','consent','locked','revision','__proto__','constructor']){const text=JSON.stringify(document()).replace(/}$/,',"'+key+'":true}');assert.throws(()=>f.h.importTemplate(text),key);}for(const value of [null,[],0,'text'])assert.throws(()=>f.h.importTemplate(JSON.stringify(value)));const x=document();x.schema='template-share/v2';assert.throws(()=>f.h.importTemplate(JSON.stringify(x)));});
 await test('guide_arrays_and_advice_are_strictly_typed_and_single_line',()=>{const f=fixture();for(const bad of [null,1,{},['x']]){const x=document();x.guide.advice=bad;assert.throws(()=>f.h.importTemplate(JSON.stringify(x)));}for(const bad of [null,{},'人像',[1],['两\n行']]){const x=document();x.guide.suitable=bad;assert.throws(()=>f.h.importTemplate(JSON.stringify(x)));}const x=document();x.guide.price=0;assert.throws(()=>f.h.importTemplate(JSON.stringify(x)));});
 await test('legacy_guide_reply_remains_narrow_and_does_not_replace_name_or_prompt',()=>{const f=fixture();f.p.setData({name:'已有模板',prompt:source});f.field('guideJson','{"advice":"清晰主体","suitable":["风景"]}');assert.equal(f.p.data.prompt,source);assert.equal(f.p.data.name,'已有模板');assert.equal(f.p.data.advice,'清晰主体');assert(f.p.data.importStatus.includes('旧版'));assert.throws(()=>f.h.importTemplate('{"advice":false}'));});
 await test('paste_auto_reads_without_server_post_and_preserves_cover_tokens_revision_and_status',()=>{const f=fixture();f.p._tokens=['signed-token'];f.p.setData({covers:[{token:'signed-token',url:'https://cos.invalid/a'}],shareId:'ts_existing',revision:3,consent:true});f.field('guideJson',JSON.stringify(document()));assert.equal(f.p.data.name,'水彩旅行');assert.equal(f.p.data.prompt,source);assert.equal(f.p.data.consent,false);assert.equal(f.p.data.revision,3);assert.equal(f.p.data.shareId,'ts_existing');assert.equal(f.p.data.status,'draft');assert.equal(f.p.data.covers.length,1);assert.deepEqual(f.p._tokens,['signed-token']);assert.equal(f.calls.length,0);assert.equal(f.p.data.importPending,false);});
 await test('imported_fields_stay_editable_and_repeated_read_keeps_manual_edits',()=>{const f=fixture();f.field('guideJson',JSON.stringify(document()));f.p.onToggleDetails();assert(f.p.data.showDetails);f.field('name','手动新名称');f.field('prompt','手动原文');f.p.onImportGuide();assert.equal(f.p.data.name,'手动新名称');assert.equal(f.p.data.prompt,'手动原文');assert(f.p.data.importStatus.includes('保留'));});
 await test('replacing_existing_content_requires_confirmation_and_cancel_keeps_it',()=>{const f=fixture();f.p.setData({name:'旧名',prompt:'旧词',consent:true});f.field('guideJson',JSON.stringify(document()));assert.equal(f.p.data.name,'旧名');assert(f.p.data.importPending);assert.equal(f.p.data.consent,false);assert.equal(f.modals.length,0);f.p.onImportGuide();f.modals[0].success({confirm:false});assert.equal(f.p.data.name,'旧名');f.p.onImportGuide();f.modals[1].success({confirm:true});assert.equal(f.p.data.prompt,source);assert.equal(f.p.data.importPending,false);});
 await test('late_replace_confirmation_cannot_overwrite_new_manual_edits_or_account',()=>{for(const change of ['edit','owner','unload','input']){const f=fixture();f.p.setData({name:'旧名',prompt:'旧词'});f.field('guideJson',JSON.stringify(document()));f.p.onImportGuide();if(change==='edit')f.field('name','刚刚修改');if(change==='owner')f.app.globalData.userId='B';if(change==='unload')f.p.onUnload();if(change==='input')f.field('guideJson','');f.modals[0].success({confirm:true});assert.notEqual(f.p.data.prompt,source,change);}});
 await test('invalid_reply_is_atomic_and_pending_or_invalid_import_cannot_submit',async()=>{const f=fixture();f.p.setData({name:'旧名',prompt:'旧词',covers:[{token:'a'}],consent:true});f.p._tokens=['a'];f.field('guideJson','{"name":');assert.equal(f.p.data.name,'旧名');assert(f.p.data.importError);f.p.data.consent=true;await f.p.onSubmit();assert.equal(f.calls.length,0);assert(f.p.data.error.includes('先读取'));});
 await test('auto_import_draft_cover_and_review_submission_keep_existing_revision_consent_contract',async()=>{const requests=[],f=fixture('template-share',{api:{request:async(url,o)=>{requests.push({url,...o});return{submission:{id:'ts_fixture',revision:requests.length+1,status:o.data.submit?'pending':'draft',name:o.data.name,subtitle:o.data.subtitle,prompt:o.data.prompt,guide:o.data.guide,cover_tokens:o.data.cover_tokens,covers:o.data.cover_tokens.map(token=>({token,thumbnail_url:'https://cos.invalid/small'}))}};}}});f.p.onLoad({});f.field('guideJson',JSON.stringify(document()));await f.p.onSaveDraft();assert.equal(requests.length,1);assert.equal(requests[0].data.submit,false);assert.equal(requests[0].data.consent,false);assert.equal(requests[0].data.prompt,source);f.p.applyShare({id:'ts_fixture',revision:3,status:'draft',...document(),cover_tokens:['owned_cover'],covers:[{token:'owned_cover',thumbnail_url:'https://cos.invalid/small'}]});await f.p.onSubmit();assert.equal(requests.length,1);f.p.onConsent({detail:{value:['template']}});await f.p.onSubmit();assert.equal(requests.length,2);assert.equal(requests[1].method,'PUT');assert.equal(requests[1].data.revision,3);assert.deepEqual(plain(requests[1].data.cover_tokens),['owned_cover']);assert.equal(requests[1].data.prompt,source);assert.equal(requests[1].data.consent,true);assert(!('schema' in requests[1].data));assert(!('guideJson' in requests[1].data));assert.equal(f.p.data.locked,true);});
 await test('locked_busy_loading_and_unloaded_forms_reject_import_field_edits_and_queued_writes',async()=>{for(const mode of ['locked','busy','loading','unloaded']){const f=fixture();f.p.data.guideJson=JSON.stringify(document());if(mode==='unloaded')f.p.onUnload();else f.p.data[mode]=true;f.p.onImportGuide();f.field('name','改名');assert.equal(f.p.data.name,'',mode);assert.equal(f.p.data.prompt,'',mode);await f.p.onSaveDraft();await f.p.onSubmit();f.p.onChooseCover();await f.p.uploadChosen([{tempFilePath:'fixture'}]);assert.equal(f.calls.length,0,mode);}});
 await test('copy_click_before_entering_any_template_data_has_immediate_success_feedback',()=>{const f=fixture();f.p.onCopyGuide();assert.equal(f.clips.length,1);assert(f.clips[0].data.includes('template-share/v1'));assert.equal(f.p.data.copying,false);assert(f.p.data.copyStatus.includes('已复制'));assert.equal(f.p.data.copyError,'');assert.equal(f.timers.size,0);});
 await test('clipboard_failure_and_throw_show_selectable_instruction_instead_of_silent_noop',()=>{for(const type of ['fail','throw']){const f=fixture('template-share',{clip:o=>{if(type==='throw')throw new Error('fixture');o.fail({errMsg:'setClipboardData:fail fixture'});}});f.p.onCopyGuide();assert.equal(f.p.data.copying,false);assert(f.p.data.copyError);assert(f.p.data.showAiInstruction);assert(f.p.data.aiInstruction.includes('template-share/v1'));assert(!f.toasts.includes('AI整理指令已复制'));}});
 await test('clipboard_timeout_resets_busy_and_duplicate_taps_or_late_success_do_not_fake_success',()=>{const f=fixture('template-share',{clip:()=>{}});f.p.onCopyGuide();f.p.onCopyGuide();assert.equal(f.clips.length,1);assert(f.p.data.copying);[...f.timers.values()][0]();assert(!f.p.data.copying);assert(f.p.data.copyError);f.clips[0].success();assert(!f.p.data.copyStatus.includes('已复制'));});
 await test('clipboard_late_owner_or_unload_response_does_not_restore_private_text_or_toast',()=>{for(const mode of ['owner','unload']){const f=fixture('template-share',{clip:()=>{}});f.p.data.prompt='私有提示词';f.p.onCopyGuide();if(mode==='owner')f.app.globalData.userId='B';else f.p.onUnload();f.clips[0].success();assert.equal(f.toasts.length,0);if(mode==='owner'){assert.equal(f.p.data.aiInstruction,'');assert.equal(f.p.data.prompt,'');assert.equal(f.p.data.copying,false);}}});
 await test('reward_copy_uses_actual_amount_mode_caps_and_only_author_eligibility',()=>{const f=fixture(),p=f.h.rewardCopy(policy);assert(p.rewardTitle.includes('40'));assert(p.rewardText.includes('首次付费且成功'));assert(p.rewardRules.includes('仅奖励作者'));assert(p.rewardRules.includes('自用、免费生成、失败和退款'));assert(p.rewardRules.includes('4000'));const changed=f.h.rewardCopy({...policy,reward_amount:75,reward_mode:'all_success'});assert(changed.rewardTitle.includes('75'));assert(changed.rewardText.includes('每次付费且成功'));assert(!changed.rewardText.includes('40'));});
 await test('disabled_zero_or_invalid_policy_never_promises_default_forty',()=>{const f=fixture();for(const patch of [{enabled:false},{reward_enabled:false},{reward_amount:0},{author_daily_cap:0},{global_daily_cap:0}]){const r=f.h.rewardCopy({...policy,...patch});assert(!r.rewardTitle.includes('40'));assert(!r.rewardText.includes('可获得'));}for(const p of [null,{}, {...policy,reward_amount:'40'},{...policy,reward_amount:-1}])assert.throws(()=>f.h.rewardCopy(p));});
 await test('both_pages_refresh_policy_and_discard_out_of_order_or_unloaded_results',async()=>{for(const name of ['template-share','template-shares']){const pending=[],f=fixture(name,{api:{config:()=>new Promise(r=>pending.push(r))}}),a=f.p.loadPolicy(),b=f.p.loadPolicy();pending[1]({template_sharing:{...policy,reward_amount:75}});await b;pending[0]({template_sharing:policy});await a;assert(f.p.data.rewardTitle.includes('75'));const c=f.p.loadPolicy();f.p.onUnload();pending[2]({template_sharing:{...policy,reward_amount:90}});await c;assert(f.p.data.rewardTitle.includes('75'));}});
 await test('policy_failure_is_visible_and_retry_recovers_without_changing_earned_totals',async()=>{let failed=true;const f=fixture('template-shares',{api:{config:async()=>{if(failed)throw new Error('offline');return{template_sharing:policy};}}});f.p.data.rewards={reward_earned:123,reward_credited:100};await f.p.loadPolicy();assert(f.p.data.policyError);assert(!f.p.data.rewardText.includes('40'));failed=false;await f.p.loadPolicy();assert.equal(f.p.data.policyError,'');assert(f.p.data.rewardTitle.includes('40'));assert.equal(f.p.data.rewards.reward_credited,100);assert.equal(f.calls.length,0);});
 await test('paste_area_precedes_covers_and_editable_fields_and_manual_instruction_is_selectable',()=>{const xml=fs.readFileSync(path.join(root,'miniprogram/pages/template-share/template-share.wxml'),'utf8');assert(xml.indexOf('data-field="guideJson"')<xml.indexOf('cover-grid'));assert(xml.indexOf('cover-grid')<xml.indexOf('data-field="name"'));assert.equal((xml.match(/bindtap="onCopyGuide"/g)||[]).length,1);assert(xml.includes('selectable="true"'));assert(xml.includes('bindtap="onToggleDetails"'));assert(xml.includes('maxlength="40000"'));assert(xml.includes('importPending || !!importError || !consent'));for(const k of ['name','subtitle','prompt','advice','suitable','unsuitable','tips'])assert(xml.includes('data-field="'+k+'"'));const mine=fs.readFileSync(path.join(root,'miniprogram/pages/template-shares/template-shares.wxml'),'utf8');assert(mine.indexOf('rewardTitle')<mine.indexOf('bindtap="onCreate"'));assert(mine.includes('rewards.reward_earned'));assert(mine.includes('rewards.reward_credited'));});
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'template_ai_import_results.json'),JSON.stringify({cases},null,2),'utf8');const passed=cases.filter(x=>x.passed).length;console.log(`TEMPLATE_AI_IMPORT_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1});
