/* Real production sharing renderer; structural mobile-layout contracts in jsdom. */
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom'),root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..')),out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/web-sharing-layout'));
const cases=[],tick=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name);}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
(async()=>{
 const {mountTemplateSharing}=await import(pathToFileURL(path.join(root,'backend/static/web/template-sharing.js')).href);
 function fixture(items=[],custom){
  const dom=new JSDOM('<main></main>',{url:'https://site.invalid/',pretendToBeVisual:true}),doc=dom.window.document,calls=[],nav=[];
  const ctx={accountVersion:1,state:{user:{user_id:'OWNER'}},document:doc,requireLogin:async()=>true,toast:()=>{},confirm:async()=>true,navigate:(route,params)=>nav.push({route,params}),element:(tag,cls,text)=>{const n=doc.createElement(tag);n.className=cls||'';if(text!=null)n.textContent=text;return n;},api:async(url,settings={})=>{calls.push({url,settings});if(custom)return custom(url,settings);return {items,next_offset:items.length,has_more:false,rewards:{reward_earned:80,reward_credited:40,recovery_due:20}};}};
  return {ctx,dom,doc,calls,nav,view:doc.querySelector('main'),close:()=>dom.window.close()};
 }
 await test('empty_mine_has_one_visible_primary_create_with_coherent_heading_and_footer',async()=>{
  const f=fixture(),stop=await mountTemplateSharing(f.ctx,f.view,'template-shares');await tick();assert(f.view.querySelector('header.creation-heading h1'));assert.equal(f.view.querySelector('.template-share-toolbar .creation-button').hidden,true);const empty=f.view.querySelector('.template-share-empty');assert.equal(empty.hidden,false);assert(empty.textContent.includes('上传实际效果'));const create=empty.querySelector('.creation-button');create.click();assert.deepEqual(f.nav.at(-1),{route:'template-share',params:{fresh:true}});assert.equal(f.view.querySelectorAll(':scope > button').length,0);assert.equal(f.view.querySelectorAll('.template-share-pagination .creation-tab').length,2);assert.equal(f.view.querySelector('.creation-state').textContent,'');stop();f.close();
 });
 await test('nonempty_list_aligns_title_status_actions_and_suppresses_empty_create',async()=>{
  const f=fixture([{id:'one',name:'一段很长的模板名称',subtitle:'效果介绍',status:'pending',has_published:true}]),stop=await mountTemplateSharing(f.ctx,f.view,'template-shares');await tick();assert.equal(f.view.querySelector('.template-share-empty').hidden,true);assert.equal(f.view.querySelector('.template-share-toolbar .creation-button').hidden,false);const card=f.view.querySelector('.template-share-card');assert(card.querySelector('.template-share-card-heading h2'));assert.equal(card.querySelector('.template-share-status').textContent,'等待审核');const edit=card.querySelector('.template-share-card-actions .creation-tab');edit.click();assert.deepEqual(f.nav.at(-1),{route:'template-share',params:{id:'one'}});assert(card.textContent.includes('新版本通过后才替换'));stop();f.close();
 });
 await test('reward_summary_is_two_labeled_values_without_balance_mutation',async()=>{
  const f=fixture(),stop=await mountTemplateSharing(f.ctx,f.view,'template-shares');await tick();assert.equal(f.view.querySelectorAll('.template-share-reward-item').length,2);assert.deepEqual(Array.from(f.view.querySelectorAll('.template-share-reward-value')).map(n=>n.textContent),['已产生 80 光子','已到账 40 光子']);assert(f.view.querySelector('.template-share-rewards').textContent.includes('不扣已有余额'));assert(!Object.hasOwn(f.ctx.state.user,'balance'));assert.equal(f.calls.length,1);assert(!f.calls[0].settings.method);stop();f.close();
 });
 await test('editor_groups_covers_prompt_guides_and_actions_with_collapsed_ai_reference',async()=>{
  const f=fixture(),stop=await mountTemplateSharing(f.ctx,f.view,'template-share',{fresh:true});await tick();const sections=f.view.querySelectorAll('.template-share-section');assert.equal(sections.length,2);assert.equal(sections[0].querySelector('[name=files]').multiple,true);assert(sections[0].querySelector('[name=prompt]'));for(const name of ['advice','suitable','unsuitable','tips'])assert(sections[1].querySelector('[name='+name+']'));assert.equal(f.view.querySelector('details.template-share-ai').open,false);assert(f.view.querySelector('details.template-share-ai [name=ai_prompt]').readOnly);assert.equal(f.view.querySelectorAll('.template-share-form-actions button').length,2);assert.equal(f.view.querySelectorAll('.template-share-form-actions .creation-button').length,1);assert.equal(f.view.querySelector('.template-share-footer').parentNode,f.view);assert.equal(f.view.querySelector('[name=consent]').closest('label').classList.contains('template-share-consent'),true);assert.equal(f.calls.length,0);stop();f.close();
 });
 await test('pending_editor_keeps_withdraw_separate_and_locks_all_nested_form_controls',async()=>{
  const record={id:'one',revision:1,status:'pending',name:'等待',prompt:'画面',covers:[{token:'cover',thumbnail_url:'https://cos.invalid/thumb'}],guide:{},has_published:true};
  const f=fixture([],async()=>({submission:record})),stop=await mountTemplateSharing(f.ctx,f.view,'template-share',{id:'one'});await tick();assert(Array.from(f.view.querySelectorAll('form input,form textarea,form button')).every(n=>n.disabled));const withdraw=Array.from(f.view.querySelectorAll('.template-share-footer button')).find(n=>n.textContent==='撤回此模板');assert(!withdraw.hidden&&!withdraw.disabled);assert.equal(f.view.querySelector('.template-share-version').hidden,false);assert.equal(f.view.querySelector('.template-share-cover img').src,'https://cos.invalid/thumb');assert(f.view.querySelector('.template-share-covers').closest('.template-share-section'));stop();f.close();
 });
 await test('late_list_response_does_not_repaint_or_reveal_stale_empty_state',async()=>{
  let finish;const f=fixture([],()=>new Promise(resolve=>finish=resolve)),stop=await mountTemplateSharing(f.ctx,f.view,'template-shares');await tick();stop();f.view.replaceChildren(f.doc.createTextNode('新页面'));finish({items:[],has_more:false,rewards:{reward_earned:10}});await tick();assert.equal(f.view.textContent,'新页面');assert.equal(f.calls.length,1);f.close();
 });
 fs.mkdirSync(out,{recursive:true});const passed=cases.filter(x=>x.passed).length;fs.writeFileSync(path.join(out,'web_sharing_layout_results.json'),JSON.stringify({summary:{total:cases.length,passed,failed:cases.length-passed},cases},null,2));console.log(`WEB_SHARING_LAYOUT_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1;});
