/* Real DOM contracts for the responsive library. Browser geometry is checked in the UI pass. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const {JSDOM}=require(process.env.WEB_DOM_MODULE||'jsdom');
const root=path.resolve(process.env.REVIEW_ROOT||path.join(__dirname,'../..'));
const out=path.resolve(process.env.REVIEW_OUTPUT||path.join(root,'audit/web-library-layout'));
const css=fs.readFileSync(path.join(root,'backend/static/web/library.css'),'utf8');
const source=fs.readFileSync(path.join(root,'backend/static/web/shared-load.js'),'utf8').replace(/\bexport (?=(?:async )?function|class)/g,'')+'\n'+fs.readFileSync(path.join(root,'backend/static/web/library.js'),'utf8').replace(/^import .*;\r?\n/gm,'').replace('export async function mountLibrary','async function mountLibrary')+'\nwindow.mountLibrary=mountLibrary;';
const cases=[];
async function test(name,fn){try{await fn();cases.push({case:name,passed:true});console.log('PASS '+name);}catch(e){cases.push({case:name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
const wait=()=>new Promise(r=>setImmediate(r));
async function fixture(route='my',options={}){
  const dom=new JSDOM('<!doctype html><style>'+css+'</style><main></main>',{url:'https://fixture.invalid/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,doc=w.document,calls=[],events=[];
  w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
  w.URL.createObjectURL=()=> 'blob:https://fixture.invalid/image';w.URL.revokeObjectURL=()=>{};
  vm.runInContext(source,dom.getInternalVMContext());
  const now=Math.floor(Date.now()/1000),job={id:'job1',template_name:'照片的新生风格',status:'succeeded',result_url:'https://cos.invalid/result.jpg',thumb_url:'https://cos.invalid/thumb.jpg',orig_url:'https://cos.invalid/orig.jpg',created_at:now,expires_at:now+86400},post={id:'post1',title:'水彩旅行记忆',story:'第一段创作故事\n第二段细节',authorName:'创作者',categoryName:'插画与涂鸦',resultUrl:'https://cos.invalid/public.jpg',likes:2,comments:1,templateId:'tpl1',date:'2026.10.02'};
  const user={user_id:'WEB_ACCOUNT_LONG_01234567890',username:'web_user',nickname:'创作者',balance:123,wechat_bound:!!options.bound};
  const row={items:[],has_more:false,next_offset:0};
  const ctx={document:doc,accountVersion:1,state:{user:{...user},auth:{wechat_login:{ready:!!options.ready}}},requireLogin:async()=>true,element:(tag,cls,text)=>{const n=doc.createElement(tag);n.className=cls||'';if(text!=null)n.textContent=text;return n;},setBalance:n=>events.push(['balance',n]),navigate:(...v)=>events.push(['navigate',...v]),toast:s=>events.push(['toast',s]),confirm:async()=>true,startWechatLink:async()=>events.push(['link']),changePassword:async()=>events.push(['password']),logout:async()=>events.push(['logout']),api:async(raw,opt={})=>{
    calls.push({path:raw,method:opt.method||'GET',data:opt.data?JSON.parse(JSON.stringify(opt.data)):undefined});const u=new URL(raw,'https://fixture.invalid'),p=u.pathname;
    if(p==='/api/me/profile')return {nickname:opt.data.nickname};
    if(p==='/api/me')return {...user};
    if(p==='/api/my/jobs')return {jobs:[job],total:1,next_offset:1,has_more:false};
    if(p==='/api/jobs/job1')return {...job};
    if(p==='/api/community')return {...row,items:[post],categories:[{id:'illustration',name:'插画与涂鸦'}]};
    if(p==='/api/community/posts/post1')return {post:{...post}};
    if(p.endsWith('/comments'))return {...row,items:[{id:'comment1',author_name:'好友',content:'喜欢这个效果',likes:0,created_at:now}]};
    if(p==='/api/community/submissions/mine')return {...row,items:[{id:'sub1',job_id:'job1',title:'我的社区投稿',status:'pending',revision:1,submitted_at:now}],categories:[{id:'illustration',name:'插画与涂鸦'}]};
    if(p==='/api/me/credits')return {...row,items:[{id:'credit1',title:'生成扣款',amount:-40,created_at:now,job_id:'job1'}]};
    if(p==='/api/payment/orders')return {...row,items:[{id:'order1',status:'delivered',points:200,amount:600,created_at:now}]};
    if(p==='/api/me/invites')return {...row,items:[{id:'invite1',nickname:'好友',bound_at:now,reward:40}],total:1,recorded_reward:40};
    throw Error('Unexpected API '+raw);
  }};
  const stop=await w.mountLibrary(ctx,doc.querySelector('main'),route,{jobId:'job1',id:route==='orders'?'order1':'post1'});for(let i=0;i<8;i++)await wait();
  return {dom,w,doc,ctx,calls,events,close(){stop();w.close();}};
}
function ruleValue(f,selector,property,width=1200){let value='';const node=f.doc.querySelector(selector);assert(node,'missing node '+selector);const visit=rules=>{for(const r of rules){if(r.media){const max=/max-width\s*:\s*(\d+)px/.exec(r.media.mediaText);if(max&&width<=+max[1])visit(r.cssRules);}else if(r.selectorText&&r.selectorText.split(',').some(s=>{try{return node.matches(s.trim());}catch(e){return false;}})){const v=r.style.getPropertyValue(property);if(v)value=v;}}};for(const s of f.doc.styleSheets)visit(s.cssRules);return value;}
(async()=>{
  await test('all_nine_library_routes_load_with_one_coherent_page_heading',async()=>{for(const route of ['works','community','post','submissions','submit','my','credits','orders','invites']){const f=await fixture(route);try{assert.equal(f.doc.querySelectorAll('h1').length,1,route);assert.equal(f.doc.querySelector('main').dataset.state,'loaded',route);assert.equal(ruleValue(f,'h1','font-size',390),'24px',route);assert.equal(ruleValue(f,'main','padding',390),'24px 16px 36px',route);}finally{f.close();}}});
  await test('profile_identity_is_compact_and_technical_details_are_closed_by_default',async()=>{const f=await fixture();try{assert(f.doc.querySelector('.lib-profile-identity h2'));assert.equal(f.doc.querySelector('h1').textContent,'我的');const d=f.doc.querySelector('details.lib-account-details');assert(d&&!d.open);assert.equal(d.querySelector('summary').textContent,'账号信息');assert(d.textContent.includes('WEB_ACCOUNT_LONG_01234567890'));assert(d.textContent.includes('web_user'));assert(!f.doc.querySelector('.lib-profile-identity').textContent.includes('账号编号'));}finally{f.close();}});
  await test('nickname_input_and_save_button_remain_paired_at_mobile_and_desktop_widths',async()=>{const f=await fixture();try{for(const width of [320,390,700,1200]){assert.equal(ruleValue(f,'.lib-profile-form','display',width),'grid');assert.equal(ruleValue(f,'.lib-profile-form','grid-template-columns',width),'minmax(0,1fr) auto');assert.equal(ruleValue(f,'.lib-profile-form','align-items',width),'center');assert.equal(parseFloat(ruleValue(f,'.lib-profile-form input','min-width',width)),0);assert.equal(ruleValue(f,'.lib-profile-form input','min-height',width),'44px');assert.equal(ruleValue(f,'.lib-profile-form button','min-height',width),'44px');assert.equal(ruleValue(f,'.lib-profile-form input','font-size',width),'16px');}}finally{f.close();}});
  await test('profile_all_account_actions_stay_outside_collapsed_details',async()=>{const f=await fixture();try{for(const label of ['微信绑定说明','修改密码','退出登录']){const b=[...f.doc.querySelectorAll('button')].find(n=>n.textContent===label);assert(b&&!b.closest('details')&&!b.hidden,label);b.click();}for(let i=0;i<4;i++)await wait();assert(f.events.some(e=>e[0]==='link'));assert(f.events.some(e=>e[0]==='password'));assert(f.events.some(e=>e[0]==='logout'));}finally{f.close();}});
  await test('profile_saving_nickname_uses_same_owner_endpoint_and_plain_text_title',async()=>{const f=await fixture();try{const input=f.doc.querySelector('.lib-profile-form input');input.value='<b>新昵称</b>';f.doc.querySelector('.lib-profile-form').dispatchEvent(new f.w.Event('submit',{cancelable:true}));for(let i=0;i<4;i++)await wait();assert.equal(f.doc.querySelector('.lib-profile-name h2').textContent,'<b>新昵称</b>');assert.equal(f.doc.querySelectorAll('.lib-profile-name b').length,0);assert.deepEqual(f.calls.find(c=>c.path==='/api/me/profile'),{path:'/api/me/profile',method:'POST',data:{nickname:'<b>新昵称</b>'}});}finally{f.close();}});
  await test('profile_bound_account_keeps_action_disabled_and_shared_identity_fact',async()=>{const f=await fixture('my',{bound:true,ready:true});try{assert(f.doc.querySelector('[data-action="wechat-link"]').disabled);assert(f.doc.querySelector('details').textContent.includes('作品和账务使用同一账号'));assert(f.doc.querySelector('.lib-balance').textContent.includes('✦ 123'));assert(f.events.some(e=>e[0]==='balance'&&e[1]===123));}finally{f.close();}});
  await test('all_six_profile_menu_destinations_have_separate_right_aligned_arrow',async()=>{const f=await fixture();try{const nodes=[...f.doc.querySelectorAll('.lib-account-links button')];assert.equal(nodes.length,6);for(const b of nodes){assert(b.querySelector('.lib-menu-label'));assert(b.querySelector('.lib-menu-arrow'));assert.equal(ruleValue(f,'.lib-menu-label','flex-grow'),'1');b.click();}assert.deepEqual(f.events.filter(e=>e[0]==='navigate').map(e=>e[1]),['works','template-shares','submissions','credits','orders','invites']);}finally{f.close();}});
  await test('library_primary_input_card_filter_and_dialog_surfaces_are_square',async()=>{const f=await fixture('works');try{for(const selector of ['.lib-button','.lib-filter','.lib-card','.lib-photo-button'])assert.equal(parseFloat(ruleValue(f,selector,'border-radius')),0,selector);assert.equal(ruleValue(f,'.lib-button','background'),'rgb(26, 25, 23)');assert.equal(ruleValue(f,'.lib-button','color'),'rgb(247, 244, 237)');const m=await fixture();try{assert.equal(parseFloat(ruleValue(m,'.lib-input','border-radius')),0);}finally{m.close();}assert(/\.lib-dialog\s*\{[^}]*border-radius:0/.test(css));}finally{f.close();}});
  await test('work_and_community_grid_cards_stretch_with_aligned_footer_controls',async()=>{for(const route of ['works','community']){const f=await fixture(route);try{assert.equal(ruleValue(f,'.lib-work-grid','align-items'),'stretch');assert.equal(ruleValue(f,'.lib-card','display'),'flex');assert.equal(ruleValue(f,'.lib-card-body','flex-grow'),'1');assert.equal(ruleValue(f,'.lib-card-actions','display'),'grid');assert.equal(ruleValue(f,'.lib-card-actions','grid-template-columns'),'repeat(2,minmax(0,1fr))');assert.equal(ruleValue(f,'.lib-card-actions','margin-top'),'auto');assert.equal(ruleValue(f,'.lib-work-grid','grid-template-columns',390),'minmax(0,1fr)');assert.equal(ruleValue(f,'.lib-work-grid','gap',390),'20px');}finally{f.close();}}});
  await test('filter_rows_scroll_horizontally_instead_of_building_tall_wrapping_controls',async()=>{for(const route of ['works','community']){const f=await fixture(route);try{assert.equal(ruleValue(f,'.lib-filter-bar','flex-wrap',390),'nowrap');assert.equal(ruleValue(f,'.lib-filter-bar','overflow-x',390),'auto');assert.equal(ruleValue(f,'.lib-filter-bar','scrollbar-width',390),'none');assert(/\.lib-filter-bar::-webkit-scrollbar\s*\{\s*display:none/.test(css));assert([...f.doc.querySelectorAll('.lib-filter-bar button')].every(b=>b.tabIndex>=0));assert.equal(ruleValue(f,'.lib-filter','flex-shrink',390),'0');assert.equal(ruleValue(f,'.lib-filter','min-height',390),'44px');}finally{f.close();}}});
  await test('desktop_compact_controls_expand_to_mobile_touch_height',async()=>{const f=await fixture('works');try{assert.equal(ruleValue(f,'.lib-small','min-height',1200),'32px');assert.equal(ruleValue(f,'.lib-small','min-height',390),'44px');assert.equal(ruleValue(f,'.lib-link','min-height',1200),'32px');assert.equal(ruleValue(f,'.lib-link','min-height',390),'44px');assert.equal(ruleValue(f,'.lib-image','aspect-ratio'),'4/3');assert.equal(ruleValue(f,'.lib-image','object-fit'),'contain');}finally{f.close();}});
  await test('post_and_submission_images_keep_full_uncropped_aspect_and_bounded_reading_width',async()=>{for(const route of ['post','submit']){const f=await fixture(route);try{assert.equal(ruleValue(f,'main','max-width'),'808px');assert.equal(ruleValue(f,'.lib-image','aspect-ratio'),'auto');assert.equal(ruleValue(f,'.lib-image','object-fit'),'contain');if(route==='post')assert.equal(ruleValue(f,'.lib-story','white-space'),'pre-wrap');}finally{f.close();}}});
  await test('credits_amount_is_fixed_right_column_and_uses_real_signed_value',async()=>{const f=await fixture('credits');try{assert.equal(f.doc.querySelector('.lib-amount-spend').textContent,'-40 光子');assert.equal(ruleValue(f,'.lib-amount-spend','white-space'),'nowrap');assert.equal(ruleValue(f,'.lib-amount-spend','flex-shrink'),'0');assert.equal(ruleValue(f,'.lib-ledger-row','justify-content'),'space-between');assert(f.calls.some(c=>c.path==='/api/me/credits?limit=30&offset=0'));assert(!f.calls.some(c=>c.method!=='GET'));}finally{f.close();}});
  await test('hidden_controls_stay_hidden_and_styles_add_no_assets_or_animation',async()=>{const f=await fixture();try{const b=f.doc.querySelector('.lib-profile-form button');b.hidden=true;assert.equal(f.w.getComputedStyle(b).display,'none');assert(!/@import|@font-face|https?:\/\/|@keyframes|backdrop-filter/.test(css));}finally{f.close();}});
  fs.mkdirSync(out,{recursive:true});const passed=cases.filter(c=>c.passed).length;fs.writeFileSync(path.join(out,'web_library_layout_results.json'),JSON.stringify({summary:{total:cases.length,passed,failed:cases.length-passed},cases},null,2),'utf8');console.log(`WEB_LIBRARY_LAYOUT_SUMMARY total=${cases.length} passed=${passed} failed=${cases.length-passed}`);process.exitCode=passed===cases.length?0:1;
})().catch(e=>{console.error(e);process.exitCode=1;});
